"""Pass 19 curated routes: ids chosen by subject rule plus publisher whitelist, then reviewed; frozen here.

Each channel lists its programmes explicitly. POOLS_P19 is the set of publishers a channel may draw from;
scripts/programme_reuse.py validates every id against it before writing programmeRoutes.
"""

CURATED_P19 = {
    # Renaissance art, patrons and the Tudor and Italian sixteenth century
    407: [
        '1-Yrpde4X_E', 'SJoulYPgCu8', 'cETXUcYJeWk', 'GgbEVDi8Zdc', 'sKXekmE9zJw', 'exTSP163sRg', 'o4YmvQt29ko', 'LSIAde47pXQ',
        'CHpbZ7HXP7Q', '2bpf9I0QZ68', '_KkOmOseCa4', 'CIO5fqW-BR0', 'Iwr42k4c77M', 'cEK26P6r6xo', 'EcCdcEk3SQ8', 'xqWTiYBkhKA',
        'Pqcd29ZBVTg', 'HsCjVqKZSiI', '5Uw5CmPSvfw', 'gmx-dWbK7jk', '2EbN-gP21T8', 'XZCumAtVE5w', 'MDJ1CP4fEsA', 'Ms6O85t40qo',
        'uUvhKwod1gQ', 'q-BUyOcul8k', '7Yh5Lu6a1YU', 'CqIz0U8Z0OU', 'paA8hqqQ-_w', 'M7Ii_iGsAkU', 'TGsHPAD-n-U', 'mCPxw_x15Iw',
        'KKvHNK2iCQQ', '1KcdgFxmnb4', 'uUu9SStRVQA', 'zR24Coi1ZGA', 'KFoNmfnMz48', 'jNkHq6QXX30', 'jnEMdwUOpZU', 'LO8M3Aiat90',
        'gleAnyyzbgE', '3Y3lkw-A_30', 'LqsVfQrStes', 'd6vEXYETRZw', 'qTeXg-XqbZA', 'n1zUbThlCdY', 'v2DklEMgL4A', 'PuFwY-czFgA',
        '-FJnzGcMWgc', 'M2BYf2SKRsI', 'kNl6hGAieeo', 'tcjeSMICLz0', 'alWbBuPahN0', '7fsM4M2bbBg', '5i-Y_mZah2U', 'rSZ83GoJ2C8',
        'ZNWSI8jcRRA', '6AFey2TDCx8', 'IAnhVvD0mO0', '_qDjxX4j118', '327azBjatjg', 'wU5e4xOwIbA', 'f31YBanoL1s', 'piP8GCOElzU',
        '59FjuJtlF4A', 'Wn4oRNSBBgQ', 'X1ZKbFz7558', 'svjdlJrlanE', 'h8KHC28K6O0',
    ],
    # African history: kingdoms, colonial rule, independence and apartheid, from archive film and history documentaries
    418: [
        'UPmfQRYImYA', 'gO2TsFNWmmg', 'J-PiMNm_jZg', 'R2DuveRGqxs', 'Pk7yPUoGdGA', 'v8my5Z0QsQI', 'T9DOER8JmSc', 'QXFkB_o5vX8',
        'HD_Ot2GaCXo', '-b_MnhPnwvI', 'yv09o_dZv54', 'K4a01h6PxW0', 'KqLObNCmd9c', 'Swudway58UY', 'mvTZx1ZcWRA', 'CEK3tyeHYHw',
        'jDWdWVgTLu4', 'g3u5CxS3j5M', 'yaHll2Goykw', 'i8qyYFNOBhQ', 'HyL0w7iCadU', 'ML32CeRUglU', 'MlRpUzSkpJ8', 'SfoPOTV4xfU',
        'BNIvuKYh6yA', 'k_sTvmRjiDI', 'lmTuE1grISs', '3JTjPBYhMnY', '1kTZ8IpsqtE', 'GgIsWpwqUuw', 'XtlVQpwfvWo', 'itPcIS2q3sE',
        'd5XIhibezSQ', 'iqtwdzPV7XI', 'QEDQP0ZjS8w', 'wzSKdWILDnc', 'NRtX2cN3OuQ', 'Hdawwjzudn4', '1wRTNJ2BkZc',
    ],
    # Economic history: money, crises, bubbles, trading companies and ancient economies (not company stories)
    424: [
        'diEVmQZ1QfM', 'x6DRBURPlxI', 'vqooGLWpXBk', 'O2pD_y61jx4', 'qtAeINU3FKM', 'fSQgCy_iIcc', 'ejJRhn53X2M', 'hjVFwqM7xuo',
        'NqUSDi-mvqw', 'S-6WNmL26wE', 'FwHEjefqsKM', '_SHhiEISRrE', 'y3Q-3GdPMX0', '1hyYdBtJZEw', 'Avs-P6xft3o', '6sM3KOYPL_A',
        'hk4THbOoho0', 'ewCs5CF5HEg', 'H5uKPUPQSyQ', 'hSxEycfjr10', 'CxLo9hMlPxE', 'O1dbtWZFsIk', 'AXLcRbLRues', 'YD9W4bKfe2M',
        'ClaNhx71XB8', 'BnDbdQa_r38', '5uqPlOAH85o', 'E5HDQUuI6_E', 'fZEwWDbXZYk', 'wJEi1lVD-gk', 'Mg-hst8igEo', '62DxELjuRec',
        'eD9ry2Lgglw', '25_WjiZnvQk', 'g_yiQBe8yiQ', 'ppO_wdEsghc', 'aIQY44LCIjc', 'XMYruhJb8e0', 'eNX4upLN2JY', '0Gpo8wKLw6Y',
        'N1dAM2rPtKo', 'kJ8HEsoI39s', '5jjdErDkDZE', '9saLsvWcppw', 'AR2Y8NU3k-k',
    ],
    # Law and technology: copyright, privacy, surveillance, platform and internet regulation lectures
    469: [
        'xquZHy2ipGY', 'duz7UXxR7tc', '678EW8v09z8', 'KoWeYEOSBOg', 'gGB8fXqsjXk', 'Gdn_jKdABo4', 'zs3e6Xqrznk', 'EJhKwG1ZLNU',
        'YTX6nxfVKs0', 'Tz6Ge0m1GLE', '0HCUByGSpFc', 'BbC9Z_HwwHo', 'ANTqtHR0M40', 'b2aVcdcr4MA', 'IVBUBT1zzGg', 'l_7D54soJXw',
        'zLdS_otJ9EE', 'q4VZkXJed3I', 'ZOtcOuFuFZs', 'fI-fb-QawHg', 'yRShEom6qzQ', 'CEctQXRCjs8', '7STJfqc2jpw', 'bK81H7-zFg0',
        'p8MCaj68Pns', '1EIsh6GrU2U', 'jwUY0jikZqI', 'Tefs5zU-iAQ', '01hhHG-mV1o', 'eJVyUwhy7go', '4KArQHLcJ4k', '9CSB0oG2KTw',
        'YFo2VcfWCBQ', '1jtTM4u4v4o', 'kNdvVzyORpE', 'kAfesltn2DU', 'UH1tQidGR9U', '31uYSLWX2tk', 'FRGgptekYf0', 'EHgqVJWBxtA',
        '7z2fmZZn0wU', 'DcZ5HJfN7Hg', 'YLrKGrUv1Fg', 'bGNPs_63DUs', 'RlmUkG3o66s', '1uOJlQ1suG4', 'doegjamgY4U', 'DKROSO9m8W0',
        '362BTlY4h0Y', 'QlVrXSP1LhY', 'KWD2v0SJAM8', 't0HJq70KXy4', 'u56GxZD9Mzg', 'uqYwRFRL9xg',
    ],
    # Technology archive: broadcast and film records of technology as it arrived (no lectures or oral histories)
    819: [
        '16NwJwAmbcs', 'xQVv5WsE0kA', 'PXWDKB5cCOo', 'DH8JYz-98tA', 'W8-54-9J9ns', 'gUaas9Td1tI', '_7_DiUpyrjc', '7Bb6yTPZrnA',
        'JZjNHnYFqOA', 'n0O4CKaB4ls', 'IpLew7igK-w', 'fBQNOji9wfw', 'KKA8yAGi3Dg', 'jRTv9S8ufBw', 'XX53VbgcpQ4', 'xwBHXx2SllA',
        'LT5bUqxGmpk', 'TChPKED73ZA', 'hbgLjB_LQ4A', 'xEoYQh6t04E', 'wstd-i_GDgw', 'wGdEZQ2fa1I', 'tF1jtnLlypE', 'GfxxRKBgos8',
        'hwOkVgGw1z8', 'yvUT36jJaMA',
    ],
    # Internet classics: famous online phenomena and the platforms that defined web culture
    290: [
        'O5BJVO3PDeQ', 'IZ7F6ELO-hQ', 'kjyeCdd-dl8', 'M6EPWjzVflE', 'Y7nymZEXjf8', 'd68b659E4F4', 'UBPg5ftCMv8', '1ZgxeX2dCnQ',
        '-wmfpoq_Y0E', 'vZlmUG00OrI', 'l3ef5tmtA8Y', '7Jsc0jnNPGk', 'R9_uRLlnXSY', 'klEVSJsM_ww', 'ibRgd9307cU', '-6TTLZzEQHo',
        '_Rt0eAPLDkM', 'h2dHqdvXsys', 'jMxz7rzwee8', '1oQF3jdaocM', 'Ex6muzQzqI8', 'EG1wvKhZk0U', 'Ku6YJQrZ2cg', 'DeQSGqfK66Y',
        'YyxtGQ-tfJE', 'MfzMRKSTgRs',
    ],
    # Buses: bus, trolleybus and coach history, operation and archive film
    837: [
        'dbw3Rkl3AAc', '4uMHDyM6CnA', 'ROqW5WbScdY', 'b8LfOZN1hmM', 'iWVMmvOswjU', 'QXky3rTWx-Q', 'OLnEL91C-QE', 'tavLt_MY7rM',
        'xdNwwAXKCUM', 'Po7EHnEeiNU', 'sLQoQqlecrg', 'fh1IaVmu3Y8', '3q-UHd9tFNk', 'QI1yM9mzCAE', '5RBysRGa5zc', 'AWvFlTz9U5w',
        'aeAlA-FkAOY', 'Vb6kM9MkD9M', 'LtYQFsiVye8', 'RZR-T0yX5RU', 'ogaufXehghk', 'QI0Fr8VBTmc', 'c2Vj-7ts2H4', 'IUJV77ZrQFk',
    ],
    # Trams: tramways and light rail, history, operation and archive film
    838: [
        'RnFVBfhpprU', 'ayNAjFWum6A', 'IpAohPgMRGs', 'w24JmFuK5M4', 'hx7rdYXUzLk', 'kBbNSAAAxis', 'vgOpj_sjFR0', 'qPvhZY1tiys',
        'jabJi9RzgNw', 'KxzVQcTJ-ig', '5bPOzpLkxIg', 'kELqQkHzPKs', 'aMc-IsEkUjI', '5vC4y-EslKI', 'sLseWel747E', 'SsbF6ZEEWMc',
        'Wl8R9zfNwBE', '0EA_Zj5U97M', '5m_t-woglN4', 'FPVa8DgO5w4', 'CcODghL1Rk4', 'FYZ7gRheqs0', '8aQivgljXGs', 'pHjxhv4csKM',
        'UNTDDfcjxDw',
    ],
    # Independent TV: ITV-franchise (Thames) magazine, personality and regional programmes, not current affairs
    882: [
        'CFY6e2r2_hA', 'S3SV0s21Vv0', '8Z7LCeKr820', 'lWzBVwsPZNA', 'eMNrdo6q5ak', 'yVULnrMOQ50', 'zx2yjuGwbt4', 'VtbIbp7aZ2E',
        'Xv8Rb-E_Gw4', 'tzqRQfHGJDQ', 'ZzIac_Tkdb8', 'RBOCvVI7ltU', 'hXcT9Lkbb8g', 'CR7K45vG92g', 'EiW8dZEdwMI', 'xjeKLSDIKGs',
        '-Hc_LCq-i4w', 'd2HujEd_uvo', 'KVfRffhi65Y', 'lzg1iKMhgvQ', 'pVN8SzDRVgo', '4LEbj-pfC_s', 'L1FAGyJo6Fk', 'BbIxHu2f5eI',
        'pE3WwpxTOwM', 'WJici-h9HgE', 'o_8Gk01yWBA', 'D_HTSQbeZhI', 'FrWQ9jBdTfY', 'YXmZfxjz3FM', 'rxNkt3ByTUQ', 'ZEbQUJ2wFus',
        'YqJOEIMpP3Y', 'ZsgOyB8ECZs', 'ucEIbBofZLo', 'XTp-99nvthE', 'FJkqQiQw6G8', 'L5xkcK5CFZY', 'jDWdWVgTLu4', 'P0_U1mvZbBU',
        'fnOGbuzHQlA', 'aLquUma2amU', 'zmncBWospE0', 'fpCOobg46XI', 'wrd-K_gQ4ZI', 'uHcQGe4u9ZY', '7JubM0_smz8', '3T4bG12Q2Dg',
        'DTukvXUEKuM', 'aVnWf1h4Zlk', 'mGcty8WJ6Vw', 'y7492n4uGp4', 'pK_5TFw_PbA', 'KuANNiXjgZQ', 'PABsDX_9U1M', 'r9zjto8aKhs',
        'bEZ5YHMY7m0', 'h-J5H7UOotQ', 'd5BhmRHblVc',
    ],
    # Sports business: ownership, deals, leagues and the money of sport
    626: [
        'JRmeqPQ-jRk', 'bgr2tj5u5BY', 'PErvrooRl8s', 'EA2QyuZ3ucI', '_cLUSrDPZ6A', 'HnJ3wxkZkN0', 'Fv3cDMbYLuE', 'AAZlf6hFdF8',
        '-Gndot6PX_U', 'kyyiwcOtGlo', 'darfw3F9Zsk', '_Ny5C3Ham20', 'vvWq0ud6O6k', '_D1HVsG7LaU', '3Ezzm7aBR6w', 'LSHAOVLS_A0',
        'OOK6QrrXhOY', 'eZtSKgjILKw', 'Fjo0fa_V8eI', 'tjbN_DuFnRo', 'PJKXsbvTBSQ', 'cyLHBQ2TtLY', 'lSor-UiLdxM', 'O_xd_McRfQw',
        '_2LfgJq-1j0', 'aTN1I-xBdQI', 'e4rTYZYRGao', 'CQs3gpBIZMA', '29PeFRHIlEA', 'oc_5qGRxD8g', 'TffR4Lh9phQ', 'ipJPXfw7r7I',
        'X5_nj5x0BaU', 'TZV7vDNMY-U', 'ngWHorCGHH4', 'CL_tK-IsrrM', 'gml_bP1Li2w', 'BtNa5sZrBgY', 'amO6p4o8qYU', 'Wxks-oaNSYA',
        'L2c6LyXlygg', '4XcbR8fx5_Y', 'n-_ECP7jB0E', 'hZ1hkViWirY', 'i5U02YMFbzs', 'NyoWePXT50g', 'vD1PYstNCFY', 's7N-xXGgdE4',
        'y4vOuRv9jyA', '0ZOHjg9q6fo', 'W-dfjXCW5Hc', 'YviiZlcfoR8', 'sWhXmf12gEo', 'Gi7Vy_2B_D8', 'k6m6h2ukSU0', 'jUjmWFYEigw',
        'bzlT6CCbIR0', 'h8m1hSP92SU', 'RHXzFmmX1rw', 'Fv6EFJnF9bE', 'wbfMYcxB_KM', 'ooAtzkcN97w',
    ],
    # Marketing: brands, advertising campaigns and brand building
    610: [
        'xBq4FN7dTZY', 'uEeFsW9343g', 'S14oSjtxk4A', 'dOIRSqNqAzE', 'EnbmNjzk30M', '2tXErqhPHfw', 'eRyKBt7bqWU', 'nvEaljYczoU',
        'aDIocMKXO4Q', '2865iB5CSGI', 'SQBQbuIGIMg', 'pw7iJKJlsWg', 'iXjhNZlqexs', 'g5VTZnhX5WU', 'WfsM2bP64-k', 'xJq6Zj6yhTQ',
        'Fy-x-sHeFJk', 'iE_bwUR_KU0', 'BJBBDfIJipU', 'k-YAUF0c12U', 'O3kfYEo7i9U', 'Gi7Vy_2B_D8', 'NA0RYNUaMDo', '4uNyb56cWDg',
        'b3Me3BZbwbo', '215Wr1wCm9Y', 'gQTJVq_P9XY', '7mlRBidTJxE', '9IJcsVc81Vo', '7BhRBVqeNSk', 'LXifG9fYAww', 'coyHcx1An_s',
        'bfPYAmE4M6I', 'i24o3agYEdA', 'yMw9Y7xhmRE', '2sTTELiNGB0', 'kefpLBFO8w4', 'YGRRFyuWQqM', 'CFivppN7XPQ', 'squZz3aDKNM',
        'UDvh1Bw5Shg', '74GUUTUI1Ys', 'HY0c1jc-voc', 'E_rX4JJrYkY', 'vLLBzUZr6-s', 'Adl5_lJfkEE', 'vw9dqka3oDg', '6EYZHuA2xW4',
        'dthCROIKYVg', '4tM5Cnem7-o', 'VR2M1My-GfY', 'nxHZNK3XAyo', 'Q74AowEf2Y8',
    ],
    # Retail: stores, chains, shopping and the rise and fall of retailers
    612: [
        'ycsVS5Me-2o', 'jZBDwAzwWnU', 'evDE1EIYygo', 'dndAoll-3AY', 'qRIyaQLiJl4', 'TlAi8R_V3Ac', 'XxZ663MPHtk', 'KtiUMAYOcG8',
        'hD4KUkkPAT4', 'vwpe4n2vO-o', 'OUocOJXQSQE', 'JFivtOmXPPM', 'Qws713t3HBY', '1__Qg1toSSs', 'l2BuRy3e_xU', '5sMXR7rK40U',
        'dC8v-wHf7Ro', 'dmdIvAl3Pik', 'qW8XvWN-bME', '4JYUo9WKkao', 'vsafvS3M498', 'pspF4a9YQ6M', 'k58Dp3FmYrg', 'YXEfgFCkv4k',
        'QgbtoL65X04', 'Cl6fWWZ5vbc', 'A8OPvx1nhSM', 'AaktzUQsIkE', '1ESzw_LTOG4', 'pPWXfCqSED0', 'XD-lp27tl9A', 'C6vixblWhKc',
        'T4DeiIlhzUU', 'gEKd_SethrI', 'PfGaI6GtTME', 'STjQyl7Kr2s', 'JZ5ZpGkGwdE', 'f33_OXNJbW8', '0-67W8kzx5o', 'Hn-eU-ohWms',
        'Rd8J-9uUnfc', 'BNpk_OGEGlA', 'Oc_GF6eiqyg', 'jnLkDaFWMX8', '-CYZdIJey-I', '-fR57xxvr3k', 'F4DeaY9i79s', 'A_jnNKtGCxA',
        'd3faIOoawG8', 'NaCYDhUHiD8', '0SP7FKMrBaw', 'bTCRkTLQYZw', 'FfRdajGlRFw', 'QW6dyjvCS6I', 'Q3uu9q5rsbY', 'J_tj4GvhdpU',
        'QododjXbZIw',
    ],
    # Energy business: oil, gas and coal companies, markets and pipelines
    624: [
        'b58b-BvWEpo', '43zfVk7GBSA', 'akihe-AtpW8', 'kCNHwH9MxGA', 'lytZxFuXZkw', 'yCLvzlAijso', 'XK8DQEyXODU', 'MXXu0G_4TOw',
        '72pGczK3j7s', 'YGDQzORZ4NM', 'PRJra_9RLf0', 'CKLx3J7U6_Q', 'Dx_C1fOT4gQ', 'vvZHjIaau4Y', 'wDAY1NNFtTg', 'evIAnt5mNGI',
        'GWlpOR6ZKFU', 'rphO_W3AwQk', 'SyFWtzTa1Go', 'b_l3eLhYbVo', 'PAZ2tMBp_6Y', 'QQQZq3s0OZw', 'QaotZsbMsCs', 'ITXy_XdhP0g',
        'oaDm6rfQ6ck', 'KN2ETuroink', 'xPVEyYlgDq8', 'Zg_nr0IYirU', 'k8tB0k2GySU', 'ibWcbk3ARd0', '6iGj5ov5vuI', '4-phprAtA7Q',
        'qWXNypHEXl0', 'e6vQo4oE7L8', 'D97NaRPFgi4', 'aT0r_yJafmg', 'QnBqAzJXVGo', 'kJOuyckvDGY', 'gTZK94-5yjU', '9dV9Dl4PdMc',
        '-SkllwUs99Q', 'Kzb2DkFiXKM', 'UjXT7jIqOYc', 'VgbRhJAVcJQ', 'HuMxQzX0uso',
    ],
    # Media business: studios, streamers, broadcasters, publishers and platforms as businesses
    625: [
        'OC5Q8RV744g', 'hm4y8uqfu7I', 'tzqRQfHGJDQ', 'PbpVliJEwkE', '9jV52f-z6EY', 'Anl11LQqULM', 'TMKG3wHdm0c', '9bXwa4YL-Z4',
        'kc8q2PH_YXI', 'KBJ8xkxFyKs', '5sMXR7rK40U', 'q8JMfWUSlZs', 'x0r7mxwklJw', 'mxOSmCDtsE8', 'fHVbFtTbEgo', 'W0A1HK9tZZE',
        'nEAgCecB-XY', 'm2YLog9H_tI', 'YdEp9MK153c', 'BnpaFrRK3gM', 'ZvLxn3km2qs', 'aPbvY3xWfaU', 'ktwuj7NKwuM', 'I_DtS73ta1o',
        '1Zcr0VdJGik', 'BrpEHssa_gQ', 'IAglYzW2B1E', 'yYQ-C1UPfgo', 'O3kfYEo7i9U', '24AH2d6sGmA', '8s58-yzzQK8', 'mv0eMCppLA4',
        'STneDI9qehQ', 'e0GrFKFtOK0', 'PvbP-jKfAzQ', '_KdX429fhkA', '8hjcb4P-KxE', '-5_EJjfCpko', 'nu0lizDhFkM', 'C1KYRMqv_ZA',
        'ZFw-mj6vNyM', 'sp0SqZkD0Vk', '07IwfwjcFQc', 'Qojf5814Fus', '01DOCnCA1j0', '7ZWUKxeIDWQ', 'jzILJXKa66I', '1W4dFNSQmnA',
        'y6hcImACUG0', 'u17n3UaH82k', 'zCO0lNfs4oM', 'z91Ql1RWIhM', 'X3JaCyDwZ90', 'D6fzQ1OFDhY', 'Yr5iEiSb2z8', 'dSL4AFtRnWE',
        'tWkRxCA5_dg',
    ],
    # Careers: job search, interviews, promotion, pay and career change
    697: [
        'plbqT4dBNwo', 'c-beGCkpcMs', 'EdNm00w55JQ', 'ZdexTf1IAHs', 'HHdowfpwbrc', 'a5_gQLcTSUM', 'w25ZjL0OqT4', 'gCg47n_TlFc',
        'BIUFr9srS78', 'Z2AachB309o', 'QG1fo7LFesA', 'Ihmq-qeA5Pc', '0HRgbb1PcDQ', '-Inc1be4zSg', 'eTsHJoMmhYQ', 'Lacbh0VoT3g',
        'WizLaDdsHUs', 'OISvlkfbntY', '1KEbiqRWOkA', 'Ns-8Jsa3mEM', 'bxIF9X9k2IE', 'AC4L_tbiwB8', 'fF8erdGR7S8', '5MZo2RoS8Yo',
        '1dI09ZGoc3I', 'QQ4UyZNXof8', 'tCehFMwjWqM', 'XmWkcePhf84', 'hNNhUxQHaLs', 'pEEq8ff2DJs', '2NtiI0Ojczw', 'drTDBBrfqSE',
        'bYoSDUkNAaE', 'd_-KZRkFwJM', '_60xikfK1uo', 'Ruz1rMyhDX8', 'wjy_GCrZTnQ', 'BS4-3IHJbG8', '5LQQthGf8g8', 'n_-S8paMO2I',
        'rEsuBrdtwCI', 'i4hb1TnAlJM', 'yyQZgCZJo1Q', 'dNdpruNP8DM', 'D-dUk2sBFZs', 'M6pT5b5GTSk', 'yp5vmeoId34', '6ih9JmOArpo',
        '5Ynh570Mtbo', 'MizKfYe-oko', 'oc6hDUZPXmQ', 'iJve-5wHrio', 'I9Ko4Z0Plds', 'Xf1utCkN68M', 'KMYsEwdZEj0', 'i-YYMxhCCzY',
        'RNuktdNhjMM', 'MbRuzz66rzQ', 'urpxkLZEklc', 'dm8bOd9yHOE', '_AezmNe40JI', 'ZU9x1vFx5lI', '8RQv766e06c', '1ZDWkl7nA-4',
        'Qhr7Cy7YLrM', 'jzqOLoorgOs', 'xsTmH3gOtlU', 'klhPu-B3N9E', 'NcD3nufvA7Y', 'oAgMKap9Cv8', 'B8mQvdYodS8', '1wrQ6Msp7wM',
        'L5lsYI0Q8zw', '6sITr5V1XdE', 'Fk9ZtVDbw6E', '4VkZaNZGkv4', 'zWOwGi2I1bk', 'Ff5793AOaqI', 'vspYdePRl6E', 'Sd4pixNKaAs',
        'RwyFtJ6c6gQ',
    ],
    # Football documentary: modern long-form football films about clubs, fans and players
    304: [
        'C3kbGGTgeLg', 'EOfSxCWAbxA', 'G5bS3edITnw', 'o4wMsl-1bKs', '0q2NzzBCf2M', 'T43RKIHCvSM', 'D3MJP_uTljk', '2KI_HCrvSbs',
        'svnk3emqRmM', 'QWV-veNHx3s', '9t-Iq-2uiTU', 'zYJQazAkQTA', 'yMHKWk_nFKs', 'vypqGUIiv78', 'yN8sV1qM88c', 'UWYWnBPbjMQ',
        'Ea9DeVodWPw', '1DXwS5LmMmQ', 'XuHmOfm_uR8', 'ecAdPAorZlM', 'nQx5_N0GccI', '-smXc2YnV0Y', '6pYWrlvKuYQ', 'Zr2BRWGtVwc',
        'cjoa5MLeBqg', '25rOmHHrGe4', '6cbWTPc1cxc', 'LvrQX7Jzw-E', 'zSsr7GYCyKg', 'pn-xzeyyBmY', 'EP_Stxg4nUM', 'td_T0N6cSHc',
        'BOtD9AFyjQk', '1lNOwpFcVnE', 'hWaT-mtSnW8', 'd40S6axtVx8', 'LUNT33dh8Fs', 'WA8WcLo6Hh0',
    ],
    # Football history: archive football film and retrospectives of past eras
    306: [
        'qX6YS6CxzE0', 'PVe-C5rnwyM', '2aUaeOw6Q-c', 'vSnaDYyHj3E', 'viEnIRCR0hU', 'VEtAeIQnYYk', 'NGfzEkACe0k', 'i6HoTFHoqZs',
        'QQ8dg_QWNCY', 'pjMALUgj-Sw', 'JSicpM7Kpp8', '5bWkEfQPOXU', 'HLtH3vduqL0', 'b_0zIPbmaag', 'BeKTJFiQef8', 'u8g6TbD8ho0',
        'M77-4-fzrlk', '3MBLnjSyKJk', 'SBEl-LF2tBI', 'Mo29jymp5U8', 'LcV7aes2z1o', 'VIjZ-waklJo', 'GOFPuOAHyJY',
    ],
    # Sports science: training physiology, performance testing and endurance science
    390: [
        'AEe7mCr-0AM', 'tIl2CMD3ymA', '61zuiF3-hDY', 'cW4Z4PdFL_M', 'IglpZPEVkH4', 'ljcoFmYhpL8', 'brGryaS0wto', 'TXCQ-lpbPUQ',
        'kYglDt1pNBM', 'rvzQXDsIUbY', 'zT-Crk_0Gl0', 'NQbg8JnPL1A', 'u-mgVZRRlGc', 'r5lMr7pJxbQ', 'l5yMz2lFgx0',
    ],
    # Sports medicine: injury, rehabilitation, doping and athlete welfare
    391: [
        'hZnKtjezhBI', 'DxkkJuBnmIY', 'N-pmeYaUhIA', 'Obt1K9IE0UI', 'QBgOtuT3MVw', 'xRGJmSSGVzE', 'mU1ZtwI0vrk', '7Xy9uqHkfSI',
        'EKWQ-hEHFCY', 'F38p7TNnwBY', 'Xgts_FKYDME', 'ZdDHtLP3oEs', 'hQre-elnFDk',
    ],
    # Great athletes: career profiles of individual athletes across sports
    397: [
        'Xjl3FNMimIU', 'YFFUiw5wnvk', 'QuqxM38qhCQ', 'wKt7ERWdw6E', 'l9Y3sjhghmI', 'c0dba3DUSQg', 'y8zid2HT3Wo', 'KBt2BMG9-Hs',
        'ojH0v0agOB8', 's_-1V_EoByg', '08JsIWZMdLI', '-GVnCdjZoxQ', '5c5MDIP9CAs', '9_Gt_h5ElCY', 'GHS9o4AbteU', 'decJoubRGks',
        'SlSB2gzvpBg', 'xCG-626Lytc', 'hCa5g11k00I', '7KByk6b2D34', 'Ar-jRw7rjaU', 'Nngw2_RlHY0', 'plXtNFwFSVs', '_gD422uuBME',
        '25CRk33DwMU', 'C8JoGmVznvQ', 'V30Av8HxkpQ', 'oClhE66YrNw', 'gO8sMo3CooM', '8OKiyFFtYJY', 'E2U1gZdbgoc', 'ar0fJzhVbA0',
        'L-ghnYexhOE', 'ySeldUhV3S4', '358Z5UgvKQY', 'u05ORT4ZCow', 'XbO9X7fMXow', 'tSklr_g6kTM', 'JI5XXxPPqeo', '-wZsyEbZVLU',
        'y2k3LSvQuM8', '7zyhvVG5144', 'NFxV0BFyC-o', 'YcN-miEBYUE', 'HFjkQ6xGsOI', 'lF2YQEjE7_w', 'mUw8WOsX-Tw', '7VXFwTBanwU',
        'PI-qEAGfZmk', 'oYgqm50NSM0', '8a0wegK2_aE', 'e2B3g6_Z-A0', 'YOBRVz4It4c', '0esaV5-KLmk', 'SB3wWrtYw1o', 'r-aBywOrwiE',
        'h2dfvG2CAL8', 'V38akI-r1_8', 'X8GIo9iS_Xc', 'mzkMYTymCSQ', 'MdmZOHlcoro', 'xuPwZSyxUso', 'ggr-4KZEk4Y', 'sKdjDiIzwM8',
        'HYBx2eYDttw', 'wGJUloUIB-U', 'b9pXlrrrnlQ', 'EKWQ-hEHFCY', 'tdzV9auqPUo', 'XFkXDFUY0II', 'M-xHuw1P1CA', 'YjlhuxQJ68o',
        'Q00m0toNS5E', 'dtu7OV42OXk', 'B4UfC9eq5gc', '-3Q914pgzg8', 'DL6VnHQEeOI', 'ppNw_Z_D-0w', 'QfBRlPOdNZw', 'Qv980HLCCe0',
        'ECQyAYSx-G0', 'Ql0b9FMzEm0', 'iFaR9navbcE', 'yFDeEmVO8pU', 'OhIzHnSKscQ', 'uOVHi6bSy5s',
    ],
    # Seafood: fish and shellfish cookery
    717: [
        'KEnJBnx5V3c', 'gx_maTlS7DM', 'T7hMBDUI4JM', 'sqg7816n6nY', 'Db2z8pFeSyk', 'cd5IlOSoLpQ', 'ah9cyDr0iOc', '5XfA2xG4k_s',
        'ncUTY6lSmSA', 'jNRXm-kLV0s', 'IfqKdl7zDiA', 'e0aUocnYlRQ', '9FyASEx-p18', '7NJOtyhkgIs', 'jX2S9bqARP4', '41r1ROt0JT8',
        '_s_x86VE768', 'OQWFa00FTK0', 'P6j4yvrAjgs', 'zi3FB2NtLCc', 'nPj5LIyBvlg', 'lkEJqrnG3V4', '7DKlH4K1ANA', 'gKw8jMn9Zmo',
        'Cpyk3TM_V5Y', 'Aw9RqlJI7uM', 'LLAaxfJpRA4', '5ucmGE0RTlc', 'E6RTKpKwWI0', 'gba_KA8eHZc', 'GckyOFCKrWg', 'eylwa6NZN8w',
        '9xG9uFu4E4E', 'jY_NpY4wmrg', 'l8-NXGFoMEk', 'LaXWfXM2NOg', 'tAdUBjMZiTY', 'qrNwxqFI2Z4', 'FUPC86PQzjo', 'PG1Pqser3lk',
        'NkFCU8oVhFA', '0xR36cpU1EM', '1GCp3mSuvpg', 'M6lvYSr2AmA', 'C195eB2C6Sg', 'eu4iJCd7lBg', 'NhUZpsedr08', '-6kYkzd3iqo',
        'HE2oedAwQTQ', '7wJLzR6ugWY', 'N-Fd4J9N7X0', 's4u-7Q6oG4M', 'sdMyin7g8wY', 'xJNCPV1S8OE', 'NDYPzJWoaKk', 'DBk5wCkKwZM',
        'JyWMN6YSu5A', 'zksM9YhApjw', 'aXtnLngm-mw', '2Yf5YngiC1k', 'Hn6OaMMYQIk', 'zEqyO5Zzy3U', '0RaBEFJWiXQ', 'RgxYbjMaAdQ',
        'fC3dh4DUbT8', 'rDNuvajZuHc', 'Rcom9v03f9g', 'zBHnhCcHV3c', 'TwbDJZx0VzE', 'DNHRXHfbOss', 'k0ZToUiOMk8', '0MtXMobfBPk',
        'xME9ftGqD-A', 'D5GaNXGqweU', 'G6BoaxQ-eIs', 'ZS4KIpb8LdE', 'lrFKBujxyAA', '5KZr7tASvfw', 'o8L8IKoTxkw', 'IioPH0YEh0U',
        'PWexfI5dG5A', '8Zxwxf-wbeA', 'MsLRAE7q3m8', 'Odsw3AzV0NM', 'gYBGiizH8s8', 'R1g38qBPJ-c', 'lTlcv2ZE6qA', '02QkjmnxPSQ',
        'PQB2tnkpQp0', '-x9A1A3Eh2Q', 'YdpyJbgUjvk', '8Wv3rBDn6ok', 'q5cfhlvh7NQ', 'sxtZtgP-wz8', 'HTHw53tZHUE', 'dJWMmwuqUvA',
        'I32oO29_FEg', 's-V0A0mIKWQ', '0dN3yTZPRKk', '1AK_RQ1uaGs', 'h6KRAKNgJSs', 'hJpE594dOo4', 'TeteYtkVB6Y', 'KEFxCGSnoZs',
        '_Af2ylgPykA', '6ouxzH0F9rk', 'qR7qouXjx-E', 'j9BOQZ9mnbs', 'dneMVHhrNbE', '905beuFL3Ow', 'K-FwSOWvV4U', 'LNWCAbUtGf4',
        'yYQp_wkVsEM', 'yIgLDiTo2Qg', 'trbl4RNgKO0', 'lB46hkwAMyA', 'i6XWJiBQbHI', 'i2WhBOx9k-4', 'xl7k56Si1Ng', 'joADP0UXFaM',
        'DvS5tq2YrAU', 'ZeiR4P3jbuw', 'zLAR8PuzCOQ', 'm3KtXhBdyiE', '7PL1JAN5CMI', 'O8SPmwrw8io', 'Ct6abtTfFfw', 'N5IghmSLiT4',
        '0ahYevAhtDk', 'n-TSSVypdHk', '6-0Y4JdRnIY', 'ijr8MCQP7pQ', '6lpwAxt-9ps', '-ORd4EBliqw', 'rJKsSHqM51c', 'ZiMvt91cHB4',
        'eZgMb2V9Cuc', '-7cbnNTKnsE', '1B8Ts3A0uBM', 'ucqj7uY2nxI', 'on_7LkCSMXc', 'ioOd9VZoMoE', 'WTxqqiuUfAA', '73ycRalPNeg',
        'rEhWSwTf6f8', 'M1NWyytya2g', 'K_xPy7J_C_g', 'w-09lisywik', 'juCFwyqD9Ws', 'cgnhm4sf8No', 'CaMYAlKk_iU', 'mx3VDROgosw',
        'k_QMtGF9QFk', 'VjUu6oyCJAA', 'Bt1cKy70o70', '4HdpdabRH_o', 'WcLYOG6-MmI', '9DrlPM-j-Bo', 'nqifUeOoTf4', 'uUUaKWpB0io',
        'FwWqh0qOYK8', 'ytxb07L5Lwg', 'rPPErmMnLhw', 'OBwqtquKkss', 'JqhhjPPfVh8', '4jh5VWk47O0', 'tMJHuhUTM9w', 'OyLaP6aomyE',
        'JpE2xWPsfyk', 'DI9sMVfcvc0', 'rUuNcHVqtvI', 'd3uZMCH2aMk', 'hPjt3TFVC7w', 'ZW0LeK8SiRM', '1LpnOV9mV6k', 'OKWFs8wyA-8',
        'NoZDXW11LcQ', 'dro3zxHMuEc', 'Z35DL_9r4kw', 'oLTe0h_UPZA', 'hheD2Ojlelc', 'ZfLyjzUiy_g', 'gdqkqjDZphA', 'PVJWmm_AQyg',
        'mTEABb1Ck_U', 'QxUfnDYxgjM', 'rQCAHMVJlcQ', 'pbcMptj4LUA', 'fMSnCYGffWA', 'z7EBv6LMhN4', 'EoDrNjsGL8s', 'GHKEChxAfC8',
        'dKNKOekkjpI', '51GpBG4iJcA', 'A_VRJtAZVJI', 'P90jTVaA6YU', '9J-KAia4Oq0', 'sn8h8XwAbPE', 'dNrxU471PBk', 'GDH6Xyzi_2Q',
        'zhu6E1LPCrI', 'csNvlSLRYOw', 'IVM4rVDpQQg', 'Xfp2H_b1bcw', 'FmsOuehAQJY',
    ],
    # Slow cooking: braises, stews, smoking and long cooks
    725: [
        'SAOS0Dw5GaM', 'llPyDvfHx3k', 'T7hMBDUI4JM', 'HlayOzgCAIU', '4nw47iAHyUw', 'J7LMjza6CqM', 'zzDAgxyxg0Y', 'tW0XoRhoUAM',
        'yUFwBBiCdMU', 'Mq7aI6QTGDM', 'D21ljhuE3qA', '3h0jPpYlCS8', 'a95Neiu3W9Q', 'DaH20w9Wh0c', '40D4kgOkkhg', 'WnyENeOaIKk',
        'YmIPT1BMSEQ', 'IP6_6Poq_Bk', 'Z2aD16zFP8E', 'n1aMiCzImnw', '5y4p5RErzLI', '-mZAUGUn5Q0', 'pTy4pXfkFA8', 'USEHE1KWJ28',
        'dnUBIW1lBnk', 'izEl02Wflu4', 'LcAIY-2SdJA', 'E7Y76CX2ZQg', 'YytF06_1bxs', '4k6TPW04CaQ', '5I9PFMc4hm0', 'M_tKnTRTUgg',
        'VDNDQxfWMfs', 'gM_-g9f3kZU', 'Im4pQaWLgeU', '-q4xy30esQs', 'XgsmkB4O7vQ', 'DzuhU8dTw-8', 'sW8aBermc10', 'mq088wp3na8',
        'BmgsBxjhN9M', 'oRZsiXtvQDI', '0i6v4b4g8Yw', 'AohVgovKI4A', 'YNBshHcxjd0', '36DsIU2DItU', 'pB6SFJ9nlwk', 'M871ES6MZJc',
        'JTVVfsSeZ84', 'zJBMPvaa6uQ', 'P2IMAO9OVJ8', '9WHnIn9zpEE', 'NBiicQZSbX4', 'aMhUXl2vcW0', 'HQ24iwau-E8', 'WUBoM9tXN4c',
        'bk8uAR5-mAg', 'dxHrb_oHM1g', 'fF1qLCToXls', 'p53xab3c3tg', 'OI2-6Ps2Hcc', 'TDUcQhOzO1Q', 'X0XpFwKKxXQ', 'VnYpoTM9ihc',
        'qsf8RlQW8Hw', '4a-nf2T04Hs', '2doMXDFOXeM', 'UPp6jLfZR4k', 'S8KpFs1CHgw', 'zk0FUS3Oq8s', '6qCVnUl0A1s', 'cQYswc4-dvU',
        'kiYo56MwzCM', 'pDgdKLLRiTg', '80YBn15kYYU', 'wHg4K27gb2U', 'uoHnQbNLiss', '0b6oMiFyWPE', 'GGQwsJqU42U', '1dHJhkwUkBo',
        'M6lvYSr2AmA', 'inO3xGew5nc', 'sVLHp5cNJHk', 'VTqC3xRV6gw', 'LoMh2HjCN9g', 'c-5O4uJrlXY', 'xrpolVK3tCU', 'v4A3tjt_dos',
        'gDnQs9oq90g', '_R_2XfDFfTQ', 'LEZOwA_Qb-Q', 'azJ4h2ybVVM', '-gk7GpHEHLo', 'b6Yqw6J8WHo', 'Dpwiulx33OM', 'cwPcgBr27Tc',
        'zmj3U1VvYdU', 'SoeAop8luqg', 'XwVnqFKz9nc', 'gyLCCZnOdTk', 'iCvk5t0YofQ', 'GISALxYcAfE', 'lpd91xBVsU0', 'Bn8UTzz5CTc',
        'NICWWnkV2I0', 'N-p3msgSZHQ', 'gT1Auo6lLU8', '4T18M-RiYi8', 'sZ604fy-xXU', 'kKQu_l6Fn1w', '6cbjIH7htNk', 'hDDZcO7s9rc',
        '4goWRdnF-EU', 'c0g1M9MQZnk', 'gAB0FwPj8y8', 'unQ3EgHqvhI', 'VBK3IX1W190', 'qrixvQzQdg0', 'OD83Cp4bLDw', 'yZDUaDDtrdk',
        '5URfsrtXSMk', 'dY7-3P7zZ4g', '5Ur3b4PH8MA', '3lDzDjpuacQ', 'DvS5tq2YrAU', 'm3KtXhBdyiE', 'WkGBczXoC0A', 'ZVMbAB_g07A',
        'RBs1XEQvy2k', 'Izg4x81lWkI', 'EQahLju1bnI', '4a-1zoZfScw', 'sKaYw_iZvJc', 'ytxb07L5Lwg', 'pXWUnP3hwtI', '5GHhST6omTQ',
        'dro3zxHMuEc', '2aHzPLE0GVQ', 'EgBV33Ci0VA', 'meckf6UDbLU', 'Y_s2_u1EI7g', 'JnfUI-abue0', 'MfcxtclSj9I', 'EZ67l5V25-A',
        'k6wOfmssWs8', 'XwjsigpNeCQ', '8M2xAMB-KEg', 'Txg6cWXPaiM', 'jBGolNzSFgQ', '709tecOPYYI', 'IgXEJjU9kIA', 'm9lJGz3M80g',
        'Pz7zEADwtfU', 'G-EjrWxM6lY', 'ZfLyjzUiy_g', '6uogTUXHcCA', '9Tmoxdx_Fqg', 'x_qaThFqd0A', 'odtbfCu58mM', '5b5JY9BOQ8g',
        'VkmA8y1g67I', 'syzKfSZiKEA', '4KPJmmwHT5Q', '1cmcI8F8nsA', 'QmFe94fu8To', 'tRMHR5KMVk0', '021KahIfXfA', 'VIdlVi-VzPY',
        '0yRT1vlwFfI', 'cvROmO5ODnQ', '4BPkJQgtHRE', '7oyBU-kMYzA', 'PYhC_mfsMU0', '2uQP2BX84Ag', '4u_bA6BcUH8', 's4P4v0LMEKo',
        'G8-qa2-ucs4', 'JU89vKmFBY0', 'JRlmQdRN0G8', 'LoDd6_u_970', '9JcFP_4v5W8', 'eD-MmEtkOSQ', '-07gtGrdeyE', '1DWB1EOLw_s',
        's0QDj0Znm5Q', 'VJBZfhGfuUM', 'x4BuEQ1CUks', '6xfp06qbO6s',
    ],
    # Regional food: named regional cuisines (Italian regions, Oaxaca, Cantonese and others)
    726: [
        '6Q6JezsHbnc', 'EgARnvcG1uc', 'ht_SfTu9KFg', 'op8h-IJ36XM', '7HYlk2I9OD8', 'ivEQC1x1IYI', 'XDwRDytcPv8', 'Cpyk3TM_V5Y',
        'dxHrb_oHM1g', 'A33iR_Lp_WQ', '0ASmeax5t5w', 'pxQfhZ8uzu8', 'fF1qLCToXls', 'jY_NpY4wmrg', 'tFQeZEfv9kQ', '0O59yp2y_Rw',
        'A8lgOrNJMtg', 'IZNpr_a14Iw', 'BQFwAf1I_Xg', 'eSR7UZqSAjY', 'x15i92Ki1FU', 'tR_IlEDeiLc', 'ichbHJ5ZqaU', 'QbdiiF4Vpwo',
        'nP70SrnWTw0', 'nH2BFkr7StY', 'T36-j3Uh1wU', 'bKIxVMQaLeM', 'TMYHbeJl0Zw', 'a2nAnIw1iaA', 'td149xSt224', 'kiYo56MwzCM',
        'qMAtITMvQUE', 'kIkioyKpUYI', 'Lr0U-ogwv68', 'GPhBSLtE4wA', 'Anmb2CaVCaY', 'zfYaQdFNO88', 'JBGzNTRZPyY', '3vIRRRptbCs',
        'anAJd69zqCA', 'mVdnnvVsk_4', 'Nc9OoguUYio', 'FaMIehBgfng', 'YGKOJ48nPVk', 'lrYu_CmDMz4', 'uQGAZ4wmxCw', '1EUuEFeshv8',
        'uhn7YZe5yBk', '2Ywptw0gDRs', 'OtBhbMIkiHI', 'w9AKF746aOg', 'bBZOjQKWQvo', 'oo56Y9s8UPA', 'wP6FfkAfUt4', 'W9h_brxTRaE',
        'wd9WgILNhFM', 'eG8iXTxVzAE', '1xHqcQqfQWY', 'gSdwQsM6XD8', 'CISmbMiCBAU', 'MloiFS-yXdQ', '4dPbEf2KERk', 'HOlwa7hKirM',
        'Z20EcrnHK7I', 'PUfCe77xtaM', 'dNlgrzFHuII', 'qQXUOJLfT-w', '-yhCN-2kHno', 'TB5YN-QSq4U', 'SSxqtDl5Fdc', '2c8J02BMC0M',
        '65P5hFADTT8', 'snuF4-xANbI', 'zbUlPb42CNo', 'pN_I5OOWre8', '1dHJhkwUkBo', 'Mh-JbtHBhAE', '0EgWTn96cJw', 'Whv52VS62qY',
        'dwuuEktZQiw', 'RL4PjV2Faj0', 'CImpPfJFyeA', 'RUpWHelVh9w', 'C12TIRf3xkQ', '63zxzfIsKzo', 'e69kesHC5vM', 'inO3xGew5nc',
        'Pq5Bvr0nNwc', '9trV5VxydmU', 'FnniNmXCG-4', 'eu4iJCd7lBg', '27k_ZOsphDI', 'lAHox_M--pI', 'OMZ2Y6L4aeM', 'VTqC3xRV6gw',
        'tk-oMVReF18', 'ykLf0AMRFXk', 'kg-lHHE91yA', 'N6YzNBcWyME', 'SjtOGNbujpQ', 'oMCJZRdh_jM', 'RSXgUovKf4s', 'WMCgV6lnT5Q',
        'HE2oedAwQTQ', 'LceCaKCCdtI', 'EPtzyEjaAk8', 'c9TtMhyqLDA', 'CD9Qohe_myg', 'YKVBhlwErzk', 'HDqK2f4oMJQ', 'XdP7EaUdQoE',
        'lqO5riRIpUI', 'RKMFhO6ydOo', 'YgCwggNfXkA', 'U1FYIOjvro0', 'zF4kQ9Qdk18', 'Zwgsbzcl5j8', 'bI60ra8AIBI', 'qwZXdEl5wkc',
        'fbKjOxiGdrw', 'rfVhbEwH3Cs', 'SPApG0YUsBQ', 'RM8-2Zn5W_Y', '5XeW9T8AlWQ', 'QTbVpQ4UfwM', '8Zxwxf-wbeA', '9H96MtF4TEk',
        '2a_HAywImBQ', 'u05mqggp2i8', '-QS0APMXLgw', '2hAFqOUn9DA', 'LQsPJupfvH4', 'ZTa1LsJAcTo', 'fB2vu2eDG90', 'acROvuObr-Q',
        'qXV0U3VfY6o', 'ObA0Rey5rxo', 'bRr8AhYFtxg', 'qcBR-fa7Lf4', 'RbzIBFaIhmk', 'G90HhyLdAaQ', '5zG907v5U0k', 'x3dvtoQYFXM',
        'dxK5n3J9pdY', 'NSAKSx4Ssj8', '9zIDLEcZrG0', 'm3KtXhBdyiE', 'BeS66yk3-As', 'Z8b3bA4R3Rw', 'JqhhjPPfVh8', 'MPxgXdTpSbE',
        'ejOaRspTesw', 'kXPGlH_0Lzo', 'nozurVDQ_Is', 'MUiKiHbgIZk', 'RQfuzVNsLCI', '6Fhp7_p4jFM', '21BZJa4amIc',
    ],
    # Health documentary: long-form documentaries about health, medicine and care
    749: [
        'MyQQiK3vn88', 'YdMCL9_UTE4', 'NOazEIijXTo', '2GLPaHa6fTs', 'bNd3Eo5bvvw', 'YAmzlo5pbN8', 'YH1wn3D9HNg', 'cGub4s1Q5L8',
        'RtGCDyfru-A', '_Zbqo_hrwXc', 'HfVW65gRPgQ', '1Ovbg4vV5yA', 'UlYC0syLe7g', 'UVvEkeH4O8o', 'EkyAuG9RSSU', 'TnF9XllKdF8',
        'uqDPJeZpmWs', 'a4wHQkU9I50', 'QdUVmB77qKI', 'VfsfFsV7rhA', 'zt2YUfC3hEU', 'SfjYuKix71I', 'IJjGYUkqFFw', 'AyCcZQ68mjI',
        'ZiBm79zvw5Q', 'UR3FmsHQSEo', '_3awb_S-arA', 'n4z71wElB3I', 'sM7FBBr5yeE', 'EwnqZ12O1sQ', 'Fd5ioKhxuxY', 'pooe2tMVYO8',
        '77TTDkR3nbI', 'EQgP153WUUM', 'qeC0-0eeTs4', '2TtVRNkpcak', 'DjuU57sCLoo', 'qPHfIKwyyj0', '-yK88XYvUcs', 'fTIYxNpb-gM',
        'cRfgEZYyDRM', 'ew62y_RrdIw', 'NQrY7WIIuho',
    ],
    # Landscape: long scenic landscape films and silent hikes
    764: [
        'BPYpFuA5mC0', 'RHu_CvNnJOw', 'oHrnBcYW6U0', 'KVKtVyhCMQ8', '6gaiAM_mIYk', '4Qdd8khODKc', 'iXI8oo8KpMA', 'Mc6LICWhDMk',
        'WKcnvPDgifA', 'fUZg6dO82MI', 'INll0-7tK4w', '7N9Pu_6_sdk', 'znBPUsMtYlM', 'fobPZUF3VSY', 'epM-GRYQpsE', 'wrhzhn3cQ9w',
        'xtDcIwh8BC0', '-ffG78PljT4', 'Z6Lr0NPZ1L4', 'lDTiQs9LCs0', 'Haeh8CpH44E', 'gSObfG9QMXA', 'Fo4unHEmZ0A', '5-XEAOerG3Q',
        'u4PmMeMFXMY', 'TzF2r0MjXK8', 'hEX-kEtiOuk', '8cQXo8c2DWk', '1xqLPRwLjeQ', 'hg6EggpwMYI', 'L4tE0hu5G_Y', 'rd-lP0srypk',
        'vju4pIWL3Dc', '7kPZkiwgA4s', '6A5HY7hDeQA', 'kE6OpybrPnE', 'a89XBgch5bE', 'vjuUoBb6cnk', 'eykT3654fig', 'AH8uBn1gWSI',
        'ozJ6xijjvXE', '-SKhQBFKw_A', '-Kc7lWsQXAE', 'Uz2KmgK-ct4', '9snqCBrrRN8', 'zJwBrfLZJUk', 'E8LEyvBTAYc', 'REIlUfIerac',
        'Jyi8cSYk1BQ', 'xNk4hAMCXfA', 'LxYT7QMT_pA', 'gxdXWG22GuU', 'YTm3Wjs_XaQ', 'suQTO6GDeUI', '91--eD6pa5Y', '2nJMWXyQpZc',
        'aURBzdjaMXA', 'JXKn1f5yVe0', 'd7qSqK9tjy8', 'ahxdsLFMTs4', 'AuHoaMBPlas', 'OKIEm0SRXKw', 'EnkWqUk2aA8', '0PhLB1Bx3N8',
        'yHseVg-sv3k', 'cFWfs5KgS2g', 'Ap8R03CffZU', 'yF1C35-wP6o', '7cZtx9xzIdg', 'tf598WCCVBI', '4diwo8BRu1c', 'uq7oBz_AX7U',
        '5czb9K8PEZk', 'ZYfpAJrIWqk', 'bfqymcyN45U', 'nNQ4MAxQ4YU', 'iL9HklKcn50', '0vsOtMwZsn4', 'y1f3OBcdeaU', 'DlZWHITZ1No',
        'VHM6bOvHZD4', 's9J50KPHVqw', 'Zj-AnS-4V6s', 'fUXB2VeNxPs', 'm9-TiEo2lMQ', 'OtQ7zJeep9E', '2c5nWCmasgE', 'QcuAyx-SH30',
        '-l4YNvs8MIE', 'oLE_b5KSgF4', 'RdG4bjrWsP4', 'vTWHKFskyLg', 'bbp6fW29Vp4', 'TCt0fHvBZls', 'zl97c98kBlI', 'ZlM31qjG8wY',
        'XVHCkO00IHQ', 'vLNlzJczUbY', 'vcexP29CSa8', 'QBKmfAwkoTg', '56EMKC1KYfk', 'BCKwWsbhwW4', 'r-bEf3vtF5Y', 'da07obpOHGc',
        'Kyclq7UucBc', 'muuZNMiZ2BM', 'Wl3Zwe8hLjc', 'xiM57jlvwys', '6on05dpifok', 'Wrg5dgzZM7w', 'CO_JZ3umpcc', 'WC5-a4adqaw',
        'bsTY5cTi3nI',
    ],
    # Luxury travel: luxury hotels, first-class rail and premium travel
    778: [
        'e4sNfERt41o', '48a30v6Kec0', 'H9YfqcQWNiA', 'TAhynE00lB4', 'TGJLlEXMSmM', 't08qGqF6UDo', 'DcQirGief28', 'evCw8DmgoUA',
        'NDIp0Vu9iII', 'JZocTmtOn30', 'KU3OmYaGYnc', 'p0MNgGI17Pw', 'NQuS2ncv3RY', 'f4rPb8FR7lw', 'qEjwcaKL5VE', '0Wyj_NHeFtg',
        'iSkz7MhNBzI', 'Rsbzdlh-7TU', 'WAdMpoBVCRM', '0p_l0_-OMig', 'tUs4oPNHNzQ', 'OrrwQr9fAso', '0LETLLl6mxo',
    ],
    # Property life: buying, renting and the housing market
    767: [
        'O2E9KKf2llw', 'b0vIPT1MlOQ', 'TC6u-Nt_M9c', 'Oc0ZoCHQKLg', 'iG3tnFWRMRY', '8Y0SY6OoKV8', 'c-n6RN8a2Zo', 'mPC9mtcYmqk',
        'nJGR-8vENeY', 'ZSfZUq1aKqU', '7HQXQR76jUg', 'pYZLblsAzGA', '-N3-AT5Ag9E', 'ot04hEWVRUU', 'm8YrTPQLhaM', '-lxBQ1D1lho',
        '6Id6FFXuqBY', 'bLtV6TtZDHU', 'PuPF8vpyA6Y', 'ChSpkZ0jVxc', '0INLWlBFjzE', 'zOHJUVSAeDw', '16eA5ebWMQQ', 'lBG-g1CKfgs',
        'j4H9LL7A-nQ', 'aU7v87EhDBI', 'q9Golcxjpi8', 'Uwl3-jBNEd4', '7rvY2rIxdsA', 'IzK5x3LlsUU', 'AKc01jo1qLw', 'UuAZ4M9f_sM',
        'AM1HJUC7YNg', 'nXcz6CHDtwo', 'f4o9aPFI3I0', 'kLQ9o3ZSEFQ', '1EgSQND6NLI', 'N6s8BdsEFtc', 'F_pKB_C1NdQ', 'FX_aiXBJwY8',
        'IZ6CZAOpw3E', 'raPu1eUvowI',
    ],
    # Deserts: desert landscapes, geology, wildlife and peoples
    440: [
        'SL_gHqnA9IA', '2P6d-9B-cHw', 'kfPc4HbaRwE', 'BNAQr6BMTQQ', 'zd7OQZ-5m5w', 'iQ5FT_7iHZA', 'noayxj2kUcY', 'gUFKiX6UJD8',
        'qesdjCIShSM', 'bsWZZlLJoy8', 't5hhkHxEq5g', 'f2clDSIcmhE', 'u730GGCrw2Y', 'Xf-LZ6O5eaE', 'zl2pAli4CBQ', 'BYxehlaneqY',
        'mpg8yJx7TNQ', '4XvPXPp8dI0', '1y8LxzPnBwc', 'Rra2m7dVXSQ', 'QDrSuudakBE', 'P9KrYXFo350', '-AzNfEd336Y', 'tX6mtqexkvs',
        'kimgkupAmTo', 'biGJ_5t30Lk', '3vkvPErIvss', 'hjez0W8SPXc', 'CA0pG9tWSqw', 'cubk66Iq4EU', 'yzOyiQGzI8Q', 'bB6BjII9Usk',
        'g6Tj-Nbxrrg', 'IMubL4OLGLc', 'j9tlXRsqmhc', 'srtEpgeTS3U', 'Bvso4Yxt57M', 'EtlZzU3kF7U', 'HAoiO2qTEEk', '8-hsUOIRVow',
        'wY9MO2DVxwM',
    ],
    # World cultures: ethnographic films and documentaries on traditions and ways of life
    449: [
        'Gj06Fn6YekU', 'n8s6U9NuUJE', 'yiGSpr1_ixI', 's1WXIwrW3aQ', '43zfVk7GBSA', 'X36vOYlh6AQ', '0_9Li81FPo8', '_IAkEQRPY8o',
        'wrSboMbXVbA', 'w3NJMY_3org', 'xz3w25j0qKY', 'SC4nwtBAYPA', 'WG9MtK2nxPI', 'Z7HPkgAtQNs', 'MS7jo0xWis0', 'uqDPJeZpmWs',
        'E9O1XBS0Aq4', '8-hsUOIRVow', 'igS9mMwQb14', 'dFCZ6gqv8hk', 'jeS7c-gnDbA', 'VTvaYywZ9HI', 'nHwj1dLFaKQ', '4n9x2n7LL9E',
    ],
    # Infrastructure: bridges, tunnels, water, sewers, grids and roads
    662: [
        'j9w7rYXvmM0', 'CI7qaAP3huo', 'vZiL--dFqCg', 'gQA8303vxjE', 'BEaJlXzjQuI', 'FDuvDi7LYhY', 'Rqx0RH7cUY8', 'pZHBpgt7kYQ',
        '2klS1diYMWU', 'lipnIdz6_L4', 'REnxH4EL5Nc', 'dStITCgn73w', 'tgeFKVX2C-o', 'm-F4oF13LXk', 'stQfGfUSLQg', '7oi4yMr8Rjk',
        'J7ieKmP96Hc', 'QOnQORqkHcM', 'nol0_4qxzb0', 'XiUOBdEUqjY', 'YSQhtlyfPtU', '-16RFXr44fY', 'XpTs1V2NQ24', 'ZwkNTwWJP5k',
        'DX_zkaK5PaI', '7G4ipM2qjfw', 'RK1J8kC1sEY', 'Seb3lULQruE', 'Yd4yxionQpg', 'vFAaXef49U0', 'PdcXkmvXXwU', 'iKNw1mnA5M0',
        'r4G0aTq5oSM', 'DdbmTl0rhGw', 'uOSnQM1Zu4w', 'CZxqVC_tBdc', 'sUoO_U_GWFo', 'kppxoA3gWco', 'ekUROM87vTA', 'UpHOkHxpTvQ',
        'e8PodEM4Y8g', 'jxNM4DGBRMU', '08mwXICY4JM', '5mCJh5SJEis', '7Q-aVBv7PWM', 'v1BMWczn7JM', 'DP62ogEZgkI', 'xNDppVTVUss',
        'eImtYyuQCZ8', 'th9XwRihDGg', 'Y-uvoaTQH5U', 'oA2-80lY5rE', '4La-8egv1bk', 'X6C2hSSUqhw', '1aqqUlv05b0', 'oP2y1eiu0ac',
        'RDKRF7utpTw', 'YZyTWRq3cTI', 'BryEmdTP7U4', 'NsyFR6stA7E', 'AXWmcvLTONw', 'pkEN9kAuAew', 'lUq5NZTGO-0', 'RbvSqEa_JpA',
        '8kqnPzznUh8', 'izLHTYaJrho', 'sZcGflbCh2k', 'c2AxOa82bi8', 'CeotdKBXmpE', '0MhsB_iD4Rg', 'm4KuSi425JQ', 'dJIlZBszM4s',
        'sVIvOLbyX7E', 'AwF72ZqJSro', 'ssZShBki6Xg', '9CRnd2Arpu4', 'fKsLa9c7uDg', 'LESdpsudU44', 'WXj_AHEfAXc', 'iwI9Uo_Ktsc',
        'HW3unjOLJSo', 'epxgK5xr72w', 'cSRCxU6dKCQ', 'YO0PruzsAQY', '7cvrQamAfvY', 'O-ImpkVH-sI', 'dYH6Gi9waSc', 'wxmGZC2i2AM',
        'gIlis57oSws', '7mJvS9QgcM8', 'QK2QjssBcm0', 'vBPhch0mGq8', 'JIXzMmZweGI', 'MOl7MsOLCyY', 'FGaUWYZ001o', 'tZenzxkgDYs',
        'W3YeFMfXubM', 'jxczIObxY20', 'possLll5Ub4', 'vlzoiL8YKeU', '1S624iIKqFg', 'WcQXlZ-OkwQ', 'GVyQmQIIC8E', 'EMPev9u2eVg',
        'Sl84gfVv5FA', 'Z3orupHbE-I', 'On-83x6-vcE', 'Wju3QwIl3OY', 'SIZqqb0noUM', 'QJC26IX9Vnc', 'pzeTidU0INA', 'oIySW_kCsXI',
        '_nBKSU9HcYw', 'uHcBkaNwfGo', 'LYqed3lDdSY', '9sQJoD_a0pM', 'tYUTUSWU26Y', 'mw4nKskCe3o', '_pmjIXLt0Gc', 'IDLkOWW0_xg',
        '777oyjIAGfc', 'qavFbOpt4jA', 'YibUi__qmrM', 'CRlZwDQUa9A', 'Kx9gj3DfP5g', '40OUCb1cODY', 'knfMZBOkIXA', 'SYm9crCpeDc',
        'YWcxlSTjOK0', '1ZUZA76L09M', 'Tw0a5y3ZeYU', '1sSlWHIyxbI', 'gIvnSe04ErM', 'mVvAopRZmtE', 'QNhupqgP0JQ', '3A_zWHgK6as',
        'd8o54wmXpV0', 'xEPswDYbcnk', '3htwtaJI2nM', 'uEgGgkTO-cw', '73EScguZZzI', 'Q0yaMq99CZA', 'WcEZOpUT3S4', 'e4DTMe0huXM',
    ],
    # Trucks: trucks, haulage and the trucking industry
    675: [
        'q-gPfvUeM1E', 'MQfJJ_irYQE', 'P96mSRZEYP4', 'M2GhwStSIyA', 'oGn0QvAT_Qs', 'Gf5mBwND4os', 'Hlha7ln8OnQ', 'd7_vUB76NAI',
        'pw250Va1JFo', 'L6_9_HHLOSY', 'OY6X_603MMc', 'CxdpcfbVAPk', 'pVz-1AHuD9k', 'hFKJFTdGJOY', 'yIZRffLA294', 'QlPrAKtegFQ',
        'xvERuWb4G2M', '8E44gC4eCqg', 'E6xeYBQ6Zlo',
    ],
    # Double Feature: publisher-presented double bills (two full films per programme)
    192: [
        'oyn-GBX4Rd8', 'KCuvUPlOtu4', 't-sK0AKVIN0', 'Zw4kqomMwxo', '3Wz82fP21zc', 'uaXSp3W7LC4', 'nhNWO8HMJaQ', 'jVD60NPQTzg',
        'MVR17IOC6UY', 'iXIN0TmgKyU', 'mD1U7zsK-s8', '49-G7-fgrhg', 'BwNpvbyuPuQ', 'iwlySuesLJE', 'UPUX6lZIpsw', 'FdhFkfTd3Hg',
        '87I_3vEiyyI', '1z32NASRt7A', '_5OZ250a6Q8', 'Wk5U71-XZ6A', 'QiuHSeyISVM', 'tB0xBrjmHLo', 'u9-vgwee7T0',
    ],
    # Creature Night: creature-feature double bills
    187: [
        'hej1LvJzveI', '0dR7utqnTqk', '_3EqD0pznaw', 'P-KWxEAbCi8', 'PESPaNw2YVg', 'XDvk9oZ9yC4', 'KzGxHcKUCIE', 'ZpRMugebGD0',
        '2SO0oIoiqmE', '5G9DieNr5aA',
    ],
    # Creature Features: single creature and monster films
    143: [
        'LSp3fqHrxCY', 'UtVZVQnKJYQ', 'I-EJAQ1oglE', 'NXHnRJqLw10', 'yHIb9HmuFyc', '5s8X3HE4LQ4', 'PQ0nR72itUg', 'bM0uvCqUFeQ',
        'jNdQ6vLND6c', '44ojLkfSlbk', 'uxgiHbnKXa8', 'U1FQDvuhJLc', 'R389WPMFhzA', 'LUBRydLeLLU',
    ],
    # B-Movies: full riffed B-movie features from Mystery Science Theater 3000
    184: [
        'srzZo_-OXEI', 'n2W7H9vKdQw', '6HnEdBrQX-g', '4sNQbqIAVek', 'lliFBNQe2JE', 'Ku6rYR1cbso', '2tyWoY4WWP4', 'eY_lHqGeLXo',
        'Tt-QLekEnA8', 'rN2VYh3Yf1s', 'Qvo_t_ofScI', '9gFEmOf7TNI', 'wHFEShYmRfk', 'X6nFNvU4mZI', 'sd_NklaAc4w', 'vJk8Us6fmfM',
        'yOMFCbaU91E', '99E3y0xkdH0', 'caKO-BZAWaE', 'u3aMHKt9KeY', 'fqrSZ9YQzMM', 'w1K8bqOMXdk', 'cBlhOrSOqbg', 'q8w2EdEsR7k',
        '55QHwLkPlik', 'RtA0g58oG7E', 'n6sOSTdl4WA', 'FFlg0jzgLDI', '_15ikumkeec', 'mg5tTEXhKJs', 'AGJ3O3KZP7g', 'MOoVR47KWPQ',
        'qbcpqw2p7y8', 'RHo5Icmk2yk', 'AE5RDDk0-DQ', '0VIA8GikYDY', '1tkGSQKrI-U', '7zIF_KSCDUc', '2hBEh1JJ1E0', '7XG0zAjYMvE',
        'C71Oj68sN5M', '5B948vMI9yg', 'MMm0kLeogwQ', '4_aIvHr5SOk', 'IdZK6YTdB4Y', '3gr9vxvAwD4', '1jdnwmWm31c', 'xo64fnJP1qw',
    ],
    # New Trailers: weekly compilations of newly released trailers dated 2026 onwards
    129: [
        'rkElwFW8fn0', 'OG521QSrluM', 'RH4B2ili8xM', '7Ciq-VzR1OA', 'P04wRyYWRFg', 'JyTKX6IDsic', 'v4-B-fvheSw', 'aT2Uajlq9ak',
        'LbQpyL4nIRk', 'QtFAyaYr1J0', 'rvFR4v3PJNo', 'EOEC-B8WQhQ', 'MYhZlrqEOl4', 'spH4LuJvAJc', 'ASCfM3eaei4', 'nxN_9HvCFig',
        '6WkuyqNIhEY', 'rZVo6jiMBoY', '6JwRbZ1J1nU', 'd8qBDXn7F0k', 'Coz2K06tUuE', 'qFyYSO8cr5k', 'w23xeHswY_8', 'SRjzyf5gk_A',
        'wrLlaAxyPI4', 'PItKTZdgR9o', '1zmpDGiYbVs', 'tMaIAfE3uKo', '_4xZe0jOEUA', '7xyOpRuzEiU', 'Rsrx2AqEGJQ', 'hbN8WDKgymg',
        'n5p5VLrB4Bo', '_DftJwT5ayY', 'Db9zVGjdLIM', '4sz9tg4MDNs', 'pnG8MKsTlSA', '_5Wf_EuM5mM', 'D0s4ErVcdMQ', 'KBXv-HgTbXA',
        'ULEfwOwALnM', 'SHtifRhLYLo', '43STit0YA0E', 'WzBj6SWm-1I', 'BhzWwpHZV0k', '4ijaGdVQBVk', '2_Swfa_l_VQ', 'ebPPz69zufc',
        '6ezPzH2hzFU', 'hEXZslPBIG8', 'jQfvXAUThEo', 'vQj4giKzSJ4', 'wuOFrcxgGW0', 'IzGSVNqTsEk', 'qfAFf8n0l-Y', 'JlBUrUJlcTQ',
        'AZ8h3L4nvyg', 'yvDGLMP_A2E', 'vuYlR47A8tI', 'ATjgiMB9GfA', 'wu04qoECPrw', 'mCOjGgm4INA', 'xJH8iCcoSDw', 'Dl1-oym-wAo',
        'CZs-qFjrmJM', 'Nz1OM1Xl61w', 'EP27oZb9Prc', 'jWwvbwm6VUM', 'XuHDlgaTUI0', 'uyRpHPWj4aI', 'mMAoM8eCreY', 'VlRwxOcqwjQ',
        '12zxeAzzp30', 'EfPLaGIP-dA', 'aW1FP2eDS8w', 'zPdwk4qqbZI', 'TFIC0FlTSR0', 'AHQO9ylv2Xo', 'X4SAVjARoIo', 'QCm3QlugtWE',
        'ZabTz3gwUGU', 'z9sPNvEFQZs', 'oH8dSiAqujk', '9hX_55aFaaM', 'YGotImFPC24', 'rcfjvjuy6j4', '-zTyWzUg1pg', 'm0GyLZqXusA',
        'oG8D_A1vTfQ', 'w3Wqrk8A7MQ', 'i6M0ne2QKmA', 'm0vurmzVsj4', '0Vdyfc6PIC8', 'a_MQgEczXqQ', 'JOBATlj561U', 'uh1_Kj9uxRw',
        'fg4oXsFcdiI', 'ILxfEpFknA8', 'BOJ3UmBHdgA', 'rdu1q0TxFG4', 'qc7vdHjVkLY', '3Vfg6PmaGn8', '6F-z_CxZSPY', 'CWExfIKtaOM',
        'TKAjbZsf9E4', 'M4JGt5C7cxM', 'pWP8Hm379OQ', 'gBdVRfENdwk', 'o7mTgt8Cb80', '6cG46EroPBE', 'qXZsV4K0p3w', 'D03Ttq1n86c',
        '0sqlYjSSUQ4', 'fr0fF53KWJI', 'oVOF8CXy-zc', '7_pIeTFUGzU', '0kmT2wZ8wGM', 'VV0BuP6Xy2E', 'EuqJ_ziA8oM', 'WzlR_0yNlhA',
        'YnjDLtL98uA', 'fMbcaHb-uT4', 'M7eOQz-lXYI', 'i4E4qaAP4V4', 'MWhTEVi1UDg', 'zLeOsNxQjrc', 'UXuA4iWWu3g', 'azbahN_5YXQ',
        'e_byt5lNEC0', 'RAuZoy2LR-g', 'biamSgxmahQ', 'gW9eLNwIs7M', 'F_e2D7MYGvE', 'iu-4SgTw73M', 'Rmm-lM33Qw0', 'MxDG0pMGI3c',
        'jquFlCZ9h5E', 'Rn5PlFGr-Ak', 'uHRUgCSvYXk', 'XhllYUwqASI', '7ZFzgOo8eWI', 'LuhxxbtADYQ', 'lsU6UBiDxvU', 'EBzivFz_aXI',
        'yv7oPAPg3gk', 'aPOW653dEVk', 'gE77VnBoLRU', 'BODkUd3nb8k', 'yq8ztEE0Rbw', 'acLnPRCJRLc', 'rdup88LacHI', '_ovPRFz8qME',
        'pZ27tWFXWpE', 'Mm7PH5HO5AI', 'zkgVzBXrEmo', 'pGqP6rLjRpg', '8uDFAz1hXzY', '_oeoStWoKgU', 'DOENZr2upAM', 'BJLtlrpsxH4',
        'mwLRdpBfNGs', '1MgCYfTHUr8', '5NeIIlsNsYM', 'Fj5m9OHkKXE', 'l3HTmm5_lsk', '1Spw95xyuMk', 'TmyJ47LEpSM', 'o-28znQlCEY',
        'tK52jX2DlaY', 'ZpFq2C9pnkw', 'JGg4UTb_fz8', 'smMvdcH4z5o', 'rTyeg8XjgF0', 'jQx54CWJ8rk', '4bXf1eEpEiM', 'FVc007hu7vE',
        'mBegRt01GSg', 'Y6b16vnohlQ', 'TaY6yRryMH4', 'Hhcai_AKrP8', 'xj66mQuilC8', 'PNatqi_3-Fc', 'w8QaksTCrNU', 'hCBR1WpGp7U',
        'TDyyLypbl3I', 'ARAJJO_h-Zw', 'tZCWKEccsRc', 'zQVK8dHbiWg', 'Ft3Qs0sMY3Y', 'JEwHjK_J9e4', '3qbonfKxygE', 'IjFAaFBInwE',
        'HNh9u_pxJVs', 'BFp8PPH2kz4', 'nuFQF7VFt5E', 't8dj4rtdEwk', 'Bx7cI3EH_qI', 'Nn7bW_sWQZg', 'U2dsTGAPfpI', '-ITiAk5sLA4',
        'xhTrd1Kk-VQ', 'mSK3FqdqCOw', 'mP1xi7sL9UY', 'H79-EqzmdwY', 'OFGqjAIW52U', 'JmX5HwLIP4E', 'swQeLIA4_Us', 'X2gBBqSpOVk',
        'UFALf0pKTPQ', 'AKfGU0kUHQc', 'a1EE9Hwy6QI', 'hT6ztEDRLPU', 'gBYr2Ymc-lU', 'EnN1bxu-ymQ', 'Cv8FxiBftDs', 'CYcAlz7CasI',
        'gUl7woPcns8', 'm5sO9JATRZs', 'apJCoZgVBsU', '9LTxCBIJLPU', 'WYJcCIf4H74', '_QBVAsUcJqE', 'UCj4V9-NN34', 'u7lfT-kH65o',
        'g46oyPCkB_Q', 'vDtO31Dk1Nw', 'QUWNWytxqJw', 'cO3MrHffZDA', 'ENGVXow7u04', '1kFxkcr3eLo', 'wUVjdquQAxU', 'QZUFUvULWqs',
        'p2ImBCSA3vw', 'uZDrdKJVv_o', '7RqbsXrHNCY', 'YFJXPXi2Bac', 'kiUtqgeDVI8', 'n8xMjVCP7Fk', 'ZtBRzqUGSrI', 'XeurGlQMJxw',
        'ecQGz0yIdIY', 'o6Dmmdpzh_A', '_vnOSSUZaB8', 'xJ_lba2Bs9Y', 'TowJ7utU1k0', '0NY6EwanV3Q', 'lhDq79brueQ', 'suFnFzUNXJ4',
        'rV8XhGRsF-Y', 'K4s04b5H8lI', 'mlfzhW4tq5Q', '-y3E20pSKIM', 'hzC5UJtf7IE', 'vJ3hKmQurls', 'Aq8k_H9tjW0', 'fOzlHMhG3nI',
        'QAmcbX_B6kU', 'MjkvOwrQNYo', '5jQ41QMN3Sk', '20WGwHEuPYI', 'egIV2R3CfV4', 'pkXBssRWtMA', '5CJzCeCusbs', 'Z1I_P7w3WKQ',
        'Ucg2hplFOoc', 'gsNA-pYy9LY', 'cY8ESBe3Ey8', 'g3pC7iFhz9M', 'bW3i2AB8D4Y', 'g33q_d4_iIU', '12vMdt4cYko', 'OiHk3tFSK84',
        'E_kJI-JqO_8', 'uqHXx73z1oo', 'fWhxkiqrh0Q',
    ],
    # Anime Cinema: full-length anime feature films (not episode compilations)
    233: [
        'PWztAiNHtt4', 'hmZBcEKfaqU', 'JJMV4WrybjM', 'YYqJMKhaLhk', 'B60vNz15Hzg',
    ],
    # Nations: country-by-country profiles of real sovereign nations and territories (no cities)
    434: [
        'Xp_TGilL9Sk', 'Fd3J0ZhJGQA', '_uL3a3aMdMQ', 'KKLY3oO8WdQ', 'ETshSZvnzRg', 'MQcrymQz0O8', 'BzMYQIo-0NA', 'kn1VrzMjst8',
        'juHLoPYaWHk', 'cnKU_osbg3s', 'pJuq8D1NGJQ', 'IWoq9N4fL9k', '-CunzmZL1XY', 'swiiVM64g6Y', 'pSnCqqTSBQg', 'tP6G2wDrUUU',
        'H8z8glfqsm0', 'xY77dfvTVpA', 'K8zAbdYx9SU', 'KtBU-HnxiCo', 'cygqKMAzNig', 'bUVHrX_WmcQ', '9ljMlfC3kUw', 'DNBCoof4dNM',
        'rsDeLmlQDH4', 'iBotvIvlCHQ', 'f_F-EYUd4lk', '8uKxaVhIte0', '1WheVxmQlo0', 'bDuW49Lxbf4', 'GwcXYTX2GmA', 'DS6i0U5ycKA',
        'tP68QwVvAZk', 'mFfJ_-XadbQ', '6QrxqHiLPf8', 'w-z4q7F5Bcs', 'ErJ6qaRhW-c', '1pxrIj9Xyps', '8TIrJADv7iE', '8Gl6iy7OEM4',
        '-eRimFrm6kQ', 'k2MOfVOUU78', 'ff4V8L_VAwQ', 'OAcbasjxljY', 'vEt3jg2XTO4', 'mnoZ1A4TU80', 'E5DV8mD9_eQ', 'VqehKH6Eq8o',
        '_MbzQNFC2kA', 'y5FPRLgQ41Q', 'AWKmazrRIwA', 'x8SLZvHOBvI', 'SU4W_tIFbTc', 'lzAESaVqix0', 'mq6L8CnNJXc', 'LVFvRNRTEd4',
        'ZRMbh0wSly0', 'bAGhXcYc0o4', 'vEy6tcU6eLU', 'Hn8XXPl1vjU', 'CqP2fiqlVok', 'oqfW7xn215o', 'h4sWFJFge54', 'x0XCXGXGZMs',
        'f4TmQEZzsec', 'Kxy74EAjAec', 'bushHvw__Mo', '8wbNEJjBa0k', 'zTK119W8MBA', 'FtZaaKFi7RM', 'mw-gmjzN4Fw', 'g0QrBphsioM',
        'yWZiO7YNoPQ', 'j3XpfBChLyk', '00QUYoZHnH8', 'xMaaUTWzv8U', '8gTkgfOMkTU', 'P722VC7b9iM', 'rr65vnslEZ0', 'MOM09fA8miU',
        'AHeq99pojLo', 'wuClZjOdT30', '9iqBeJnsq8U', 'Jim_NG0PYpc', 'FsXc3FcWi3g', 'TpdGIPHPBwU', '2xQM4Zy5zIk', 'B5flHlEkgrU',
        'Cp3yabqF4Uw', 'ZtoZlLj8t1c', 'gZ38gYvhiZA', 'YHQqsx9wsnc', 'vvgLLqpRT6s', 'G_KMybIvv4c', 'DWyjf9dhL4o', 'ZDo7RwB0Zdo',
        '5Twr04-ViR4', 'dV-H1EKmCxA', 'dD3ZFQ62Vxc', 'SxhUsPBFPkU', 'rTsPaAIJdnw', 'tzXARwHs-YQ', 'BElOyEjTujk', 'cARe_1cRj6E',
        'dbmZQDySpzY', 'WqHUQMdXDQQ', '9Yxwjy4pvsM', 'JFfcD-SkqIc', 'rTiLTnWM7vQ', 'SrOwkNEHIlk', 'S_pUIeE4Eko', 'wRzXi8DDrX8',
        'jdNw0g7SOMc', '_gSBvcYOuu4',
    ],
    # Food business: food and restaurant companies, chains, founders and the food industry as a business
    628: [
        'DyRtjgIpli8', 'myv7yydtCKc', 'RmZJ9rz7Fik', 'yG8vp_UkCVg', '1vSOoy9PEBw', 'AbwzCJ7GCec', 'MII75xjp5I0', 'oZuz9AHe9JA',
        'IlZ51zeabhM', 'h7r8ykrEKfs', 'oEnRJsSq1yY', 'IuSppv0uOCI', 'cdbypIh-1lo', 'CQzvxR2i-3s', '4gtgZdWVD98', 'o3ys76zj_ck',
        'Dgmii3eOh88', 'zUN9KQpUgzM', 'froFMqsOf20', '58Zyf6beY1Y', 'lEk5gxPQowI', 'nHuL1FqlgyA', 'zdbQSeGhbRk', 'rsC-uQgeSgA',
        'XiEb39LoESs', 'nThsHXjrpvc', 'cT0J3WjXZVc', 'UW7oUNwmHs4', 'fLkwjjUr5Pw', '3-IwjYNb-5E', 'drSLH1GmKmE', 'oiYfI820dew',
        'KAZmHIiN8VI', 'MYGZZKTA2qI', 'aIgmMXZ7008', 'qnKJfxeSImo', 'gx1DHHrxE6k', 'nqn9Bzoa04E', 'Q-8nM3ydZw4', 'w6V7CILdVJM',
    ],
    # Festival: full sets and broadcasts recorded at named music festivals
    85: [
        'GQ45vXd9VUk', '9PjwMg8XPIc', 'uxOGYRbx1kQ', 'W-qsEcxzoVQ', 'H7RC_MvuG7Y', 't2oGSlsw9R4', 'VKIa30RrLUg', 'ghu67BZD0Yc',
        'I4ls-giLvkw', 'q1VJb0MtdH4', 'xN2uM8OpGhQ', 'lO2hc_Dd_Kw', 'lmYvljOX6gg', 'E-cDHK3aAOk', 'NxKYtial5G8', 'F53ujV0CLYU',
        '2VULgCKai6U', 'xcdglZC72qg', 'J5XPIbU21io', 'bAElcYDbNK0', 'nuRZhaYeGhU', 'vpu84HqnEpo', 'Q16qor-OOy0', 'P-jLBxpbJ9M',
        'GxaPD-z9NxM', 'NfhWI8hcTv0', '4YLITg1auXQ', 'V50RMpcnJm0', 'Oiqq5MECzZg', 'DKPW0gB8XH0', 'sPPUzIDJvhE', 'LTAuOtSUjdk',
        'niEmO_8L88o', 'leto8KBC66A', 'qznylyFdOMQ', 'eMHjtQc9HBk', 'LaLt90jT96c', 'M1XGycZJZo0', 'cQ6V4DFT54Q', 'bNDgKy_M17c',
        'NHoEcIpZX7w', 'lETWqbOJ4nI', 'Z59dKFYkU2o', 'bIPhRn2ogcc', 'Yf7XDZOe0RQ', 'isAD_6KqA9Y', '1r5d-r4e5jY', 'FJn8P2cCo2k',
        'ROE1cAckW9g', 'VbnIp2j96NY', 'vWDC6A7Quek', 'UzjQdtdP9aM', 'RxXbFxvTZ7s', '0cEAGxiQ9pE', 'jtQEJu2Ek1M', 'jJbRKwGbay8',
        'kflPzUS4f90', 'P1c3JV2v1nI', 'AacMD968Sp8', 'ldUnX2RRIIE', '56pXtHGNnlI', 'meKJa_DxZw8', 'qeMsHsG2EU0', 'kVJ9ySmqcpE',
        'IMhr4eYek5w', 'Laxxsh950eM', '0i-i00P9k8c', 'T3IXGTm45n0', 'm5p1IDH0XDI', 'oqwSyP-oQt4', 'pAJFhRs5IME', 'GSijcRQu1cc',
        'oonjBzL5pNQ', 'fXXcy4RW3bw', 'HDxUze7WOEY', 'a7Vz0HCNfQ8', 'nCouZT0_Fgc', 'nzsdmEotgek', '2QIvjt3Kix4', 'z4aK46kZ5RQ',
        '8W2W1PJFSVI', 'oWFygNatjhU', 'z_9WlG3tVEc', '30jjkQZyZrI', 'sU5FtfO800o', 'fidkeQktMcQ', 'eFhsH3j4fOU', 'Z45Km9__WEQ',
        'cdFHE73aOMI', '5j3WlHaChkI', 'piT0qHk_PFg', 'SiDy1bf4P2I', '_YLs4Sfp0x0', 'sSn2z36jEA8', 'SERzPxEADmo', 'qpLba-JKsrg',
        'MY-iCMXWO2M', 'W_OyMM8lyn4', 'rTKh3LgMgeY', 'erAR5S0mBsU', 'UdNXDd3SclU', 'uZqSfooAZKE', 'tTq5nbOsxeI', '3XlcGRnT6a8',
        'BVkRpNigoXA', 'Ny9Y683nzYk', 'mnEiX38DbhU', 'ZC91KIPNI8s', 'l2n57phCRZY', '22oK7Wk7zsU', 'qVRj8-t4PwI', 'FUtaPNY98A0',
        'k2JEQ1vej6M', 'ENOEyGnc2pw', 'UfSNblVZdG4', 'F-9t1B6nmdU', 'lsiKG4AkRqI', '8EqeVZ4sGLw', 'C48OH0NE1TA', 'AKyoe_oaH_E',
        'JdAboqblhxQ', 'x9ZAjGBW2Uk', '2IQUNXUeuKI', 'L-NUQTeiPxM', '7VSUaQw6JWs', 'PGGmYKyX-fU', 'lHF7lsk9mco', '9omlmxK9Wfw',
        'HSeGs1PgHdo', 'X-CWekChOD4', 'vjhOmEEMPTg', '_DDI76wdppg', 'F2T17JvANqA', '-sYpLE1w9xk', 'jnHP3jDHrtE', 'M7ZY_FO2nnE',
        'Z31T7_8IFH8', 'PCHklKo9RVQ', 'v-SzPfrWYAM', 'FJ64aHHzSEg', 'xoqa84dZZ-I', 'zVRaSTG6GFU', 'U6230y5d8io', 'SRmTv45Wteo',
        'SWiUqDM3dGI', 'tRvil8BU3Ac', 'lvcckH2IVU4', 'lB2yM1vMoIM', '5aUIEuiGq3M', 'YbFXiX6JACU', 'bhj1kXQFtzo', 'H2Kd7VcuytA',
        'FV6Fi6fdcqY', 'bk7s97c8f2g', 'X3gsr0RL8Io', 'UX5vjjwPkgI', 'BfZAPBzopuY', 'i6uAA1ECCDM', 'g5b8mPP282w', 'd46GLypOzwg',
        'x1hp7j0ihQI', 'r0Ek8iA0vVY', 'UlReCdqNLKY', 'tDBgFrEm5Dw', 'qPSH0Og0FH0', 'G0U4TVrcmgI', 'X6ko4cklXjs', 'dTkS-zWOQVU',
        'YgBwTcpskgU', 'Easqg4SUl2Q', 'AtZxg-OC5ho', '8ClF-beNXII', 'ad4IAkS-1-w', 'rTLmeKV7j10', 'B45M8XBx3Uo', 'QlMRsaCBOzI',
        '8PWyJ9oOu9U', 'gLnkyDVmrps', 'PJ2uF2Iec3c', 'X-T-mnvCFoI', 'sW29eaaISUM', 'EsgnAaW9ywE', 'jMq23mX9ZMI', 'jjwilAja7Lc',
        '9s6pCbznmMU', 'xUkeB99Sy_c', '12p9J5YZb-A', 'DzwwDgUIOcU', 'GbUfRlHsZ3I', '1lGVcGxfgkc', 'XxfzEDHeh7U', 'T332qdYjaj4',
        'h9qZZguPIZI', '67pgcEfH2DE', 'BqClh8IvVMQ', 'QbV_LwxmaOM', '_qvERtZ5_pA', 'fbgrMht0324', 'PavxkOGhGIk', '3HxCCOqhhiY',
        '0broK9R1_q8', 'oSWzUDwxX4s', 'Kp9jroKpcNU', 'APOOfwImatw', 'O74rr3rK3_Y', 'NGL2lFFgC8w', 'Nt14Qico6ig', '8_V-N928Jkg',
        'zbpmLIrJB3Q', 'G2_Gcdpe9Mk', '6IRV8TKW5f4', 'AXz05MBWSZg', '5eUEUZ-ytJo', '3z9WKae8P9E', 'ya9ECHh1uyQ', 'JP-NwWK1Xfk',
        'Ruos-F0rCcg', 'XUbvtB15di8', 'LbFOLWUr7BY', 'nQ_mcl-snag', 'wRrMD2td9cU', 'zMf3-sOG7mo', 'nBch9aYOTOo', '2vb2mcbQLa4',
        'TCfwfOxLZWI', 'zpOww07P2l0', '9pP8ZBkJh-c', 'CUPW4XTHOWY',
    ],
    # Family Film: full films whose publisher genre field lists Family (faith-based titles excluded)
    118: [
        'jAYtNYu5pp4', '76aSjLj_Qqc', 'OXAYtbhNfyM', 'G3Zoj1acTjM', 'HKmeRbjOIl8', 'fIhM9MiEN50',
    ],
    # Artists: long-form interviews with performing musicians about their careers and records
    563: [
        'vxP9kKzbCFA', 'sYpKg6HR1z8', 'OT_KFCidz_s', 'QEgalcH_-b4', 'TqqwkvSCg5k', 'TbeevzNmU1g', 'tbrXN7x623U', 'YDdHdKtD-uM',
        'Wk92euS94nI', 'ETqm3uys9ek', 'nAfkxHcqWKI', 'jyKjADpkDLs', 'tU745UovT2g', 'TnRoHPaTFqA', '6uusF1iie88', '4nBbzajS29o',
        '_xNR2VHOzcY', 'zBfdZW96iD4', 'PzalOcJwW5A', 'O3FI4nBXE18', 'L7qf5wKOv90', '8sPpncwIHqU', '_Jxp9k72M1c', '1zXKdVdSnnQ',
        'GmA49M9HwYA', 'N_SHZkqsIDQ', '0_pdW5IyRQ0', 'FXlZT_R2Eu0', 'M1ynEx-xiN0', 'ul6COVBiKiQ', 'XIJkRhd1CTY', '_diG9PZ3CKI',
        'Q1Bebf3Y2rk', 'jqAqvIYxEuA', 'CHhqTM4kKRo', 'GLkvbCn3xbw', '_h0kgHWb6mc', '-7ik1NeS4lc', 'efRQh2vspVc', 'qMVZtd7XKcQ',
        'MReU0doapdQ', '1p5-oikCHpk', '5P8UZ8cp5co', 'PLIZZ9lIlwg', 'SQVZ1J0Mvlo', 'O3OazxoPRK8', 'vznSu-BHyVA', 'tRA5ai3ooHI',
        'l1CeYYEKXw4', '-QBabd3dYPc', 'NIJptbMOFbI', 'TToz0QP25YU', 'xgL30jDhoQU', 'k2vqJ78VA4g', '9VOw0oomUEY', 'u3KMcq3gOXM',
        'rASUoqbHhqY', 'JlENxNsHTVc', 'jZClkvwrH0c', 'WYElkX6nLvs', 'AYdmelm9ADM', 'qUz75pYsA_c', 'uBqHZGoEarI', 'L0ggtr_9GKI',
        'WzAmjmUDuZw', '2T_Dwzm31Uc', 'SakarjeEipg', '-BjdEymoy68', 'wy6ZO1e4W3U', 'iRg13KGb-28', 'rO2ETXGtlTc', 'qChcyrio5kU',
        '_3c_6dXLa2E', 'mWib02yZmKc', 'SB9xtOOGraw', 'OuCscgfbtw4', 'wDBsu6ZoCAc', 'S96obV7GvYY', '1c9lx0KFkO4', 'RJc1HN2PxXI',
        'hs23nSnBYzQ', 'nrYBUoGEFz8', 'jv3-bs7GWfc', 'oRH1G6ZpuL0', 'M6fJ5Nx_X5k',
    ],
    # Fantasy: full fantasy feature films (publisher genre field or title genre), no TV series
    37: [
        'hs7NLhk9I-Y', 'GqoNVON_ono', 'eQ6y6I_dqsE', '0WEAnm6NbV0', '9joVurTq9OI', 'sBbaiPxYC6Y',
    ],
    # Classic Horror: pre-1980 horror features, genre and original year from Wikidata (film_years.py)
    141: [
        '-n7xjZolXXc', '4K-uyJMf1C0', '4rncPEsx-uo', 'Dg8IvWeqyoE', 'Pwm5x0XvmyI', 'V5Yi_58uWQc', 'X0Ot4YZVfJA', 'bNjoCeesc5w',
        'gyJ2FbqaFGU', 'n_uQx8Eu8AM', 'op2NZq_GTHo', 'ssF32Y-eeNE', 't9P5bnR4ymQ', 'tMuXUikwluQ', 'u27_prAzLnk', 'vKLVDuIkjU0',
        'xEN3TB6mwgo', 'zPFtcSJ16ig',
    ],
    # Classic Sci-Fi: pre-1980 science-fiction features, genre and original year from Wikidata (film_years.py)
    145: [
        '4zpWLYJ49K4', '6CaWdp1IkOg', 'DAfbQlGgsfw', 'Ewp4uEVsjH4', 'Hf1URH3XZRw', 'KQqcFKLQa3I', 'OWM1IE3ADvQ', 'SG4cF8hDaig',
        'Z16BAxbJ10Y', 'dxzrWs8Rqio', 'eQjBdyQ1vkg', 'eSlcjDjCaGk', 'gZgeRNO65lI', 'jL9RPONQoZ4', 'pz140zol-eQ', 'rtFRTeHmXYM',
        'zlbP5rCuyRM',
    ],
    # Experimental Film: NFB's own director playlists for Norman McLaren, Evelyn Lambart and Arthur Lipsett
    116: [
        '-uHxsC5xXvM', '2NFyBwcnsvM', '5NOkimmCU2U', 'OoTzMJ5wVKc', 'YN9Iu0z2waI', '_Zd8NcYI9JA', 'blQLjKzZbv4', 'e_aSowDUUaY',
        'kdYhzRjHo8g', 'lA8uLEh5nyo', 'vQ3DSFv4vAg',
    ],
    # Film Noir: classic films noir (Wikidata genre film noir, verified original year)
    109: [
        'uVHzn5kmw34', 'FnFHJK2CYKw', '3nmTUKHe8dE', 'o21zaU_i6SM', 'giHMEsmUl54', '9jzYPFtrAf0', 'Z6FSseGGG3Y', '0ZJqhR7Fw2Q',
        'g2SUpL2uCg4', 'ui19MwNK10k', 'wsRBLzitFOA', 'fr74PsJwXUk', 'BITgXwcQPLc', 'XHBhkJXny18', 'K6FECsHdYHI', 'kgbLrfh_2Ec',
        '671z0iLsGYU', 'Gb_AusZ5BFc', 'rHhFViV4pnI', 'K4fChYihPQ0', '4MBLJcr-dt0', 'znkVyl10VJo', '-FmfGfrn6pE', 'SCZC6u2z4tc',
        '837FHf9mPwk', '0dko82nSPaA', 'uisCLKbEvNk',
    ],
    # Silent Cinema: silent features (Wikidata genre silent film, verified original year)
    110: [
        'w58cpgUkGTg', '8p4F8wjjJl4', 'rMen6qEO39g', 'u1_EcSIwrVQ', '-SmwZ144F6E', 'f8L4yPQbIQY', '2JHydgbK9lQ', 'jMIO121kLNY',
        'NJfYuB-eWUM', 'Jaf4bPf6EGY', '3Z_yzvvyr-U', 'LapK7MAB8ow', 'cl_Ar2ljDSU', 'JOJgt74lznA', '0yLNxYVQz3s', 'Gmc7tWB9Kq8',
        'fBfNI19CY6Y', 'WpjS8fanp-g', 'qt3YlyrUmvQ',
    ],
    # Saturday Matinee: classic westerns and the publisher's Classic Films for Kids strand
    188: [
        's8VmSvxHLFM', 'g69KsljFUUc', 'QFUq1FMW8jI', 'pGTwiu9s-Vk', 'b2OlYD6EXh0', 'DM89b3gAOLM', 'ggXjGGgrMbU', 'ffb9d7wsHsU',
        'lPG-O0DEaVI', 'yQh4ZnDLmHg', 'QTD-aROY0DY', 'itZE8vLQ4S0', 'pZAwbtz_SW0', 'kIO3ZP1ojU8', 'VDLy8ttXAiU', 'peN2O5o9p-8',
        'GnuqHZWv09o', '9M4-sfjK8Xw', 'YkTWk54pUHo', 'YO-i88TiFh8', 'VUvClLW9QgM', 'Gj9NbdRvXcM', 'JW9tmO4UFzo', '9pXYGpSSnCU',
        'NPlZBjegQas', 'EmA2h4HLT5I', 'nW7q2UOhJbw', 'JYD66N0CXos', 'KVOLC-lf4ME', 'PGL-s_GPwTs', '0i7e_pCbIY4', 'H_ViWe09j6c',
        'CCvhHOs9VMU', 'YsG2Hc6dA_s', 'BD7zxcyCM6E', 'BVq9uJjgLoY', '5DG0uPfv6Sg', 'XVgKV1587-A',
    ],
    # Sunday Cinema: classic musicals, romances and romantic comedies
    189: [
        'cq10ymHJEfg', '0eKx5JNz_Bo', 'mbkhx8hb0Pc', 'Az0-uGgIM_E', 'KRIVFF9TKtg', 'MOpChZdgWN0', 'd_R_DsTMpx0', '278b4ecs3qU',
        'Zjj3qCDtssk', 'kCd_zH-6j2A', 'O-GnzyvLDVI', 'RxBwHQSbUdY', 'rSW1PwNusTE', 'fCug2WRGHeA', 'QVY5HRN8QGQ', 'WIintQhxdu8',
        'sEL49WosPBs', 'O6RY1YzIFaY', 'gId6J12RmM4', 'qMPEhE-wfq4', 'uP_r2fWBi9E', 'lcDpHCq465o', 'vC_govTy_4g', '4ZEWmcfSbOU',
        '7HQ1BTsOy1k', 'lPVeJcM2_Uw', 'pCxCk2Mkzds', 'neyPHEpbOy0', 'rL1TSbb0iWc', 'xykmn6J2hcQ', 'aqNs5ll0-ss', '2l-CQ5Y14lg',
        'fn0kCoVzjI8', '2jNNBNX2apE', 'rPRgouXgC7U', '3u2kXZDD6L0', '_UeZI5EulyU', '3_9kMtFgtqI', 'sBUNlaPwfHM', 'x_MNopRU7cM',
        'JazE4Nm9M2Y', '8DXe144bxpo', 'LOCD9wJojA4', 'OX7atcWwrOA', 'wXWXmb5MC2k', 'JvCiDjDpdNU', 'BTMDAIZ5hy8', 'bWOU-4Ij7v4',
        'BCEGrunW6TA', 'REsXObJ5s3M', 'v1YxFbhTtbk', 'UyPYPid79Fk', 'JkCSas9dcpM', 'TCdPJ0xcyes', 'tjKNeYfuFDs', '_oYy8nEXF5Y',
        'zxnNoIOsYYU',
    ],
    # Late Film: classic crime, mystery and thriller features that are not noir
    190: [
        'VoMor4M1Ssw', 's4i4P8LziUc', 'T1I6iWTQLdo', 'gR--SsQMUqQ', 'FXL6G3psIkI', 'SwliK-Hvi08', 'QHiHmsVoeVc', 'C7rTx00lcss',
        'WcqSILHzrx8', 'aMDfd5nmkaA', '_m04DLTNBss', 'CNiWN3F6UQ8', 'x-itMUUqdFI', 'vhNN1o9ABC4', 'ITkjmuu4EC0', 'H6XJTxC0bhU',
        'VQD2VCRNwg4', 'w7dQbMM3fcw', 'fdUNiaX2iwk', '43AX5pGYabg', '2d3oTiRezTc', 'cQ_1fj73dHE', '0fcXpQgoUZ4', 'SbEeTBPBFLE',
        'xwEfaCpT7F8',
    ],
}

POOLS_P19 = {
    407: {'src_bernadette_banner', 'src_british_museum', 'src_christies', 'src_english_heritage', 'src_national_gallery', 'src_sothebys', 'src_tasting_history', 'src_time_team', 'src_timeline'},
    418: {'src_ap_archive', 'src_british_museum', 'src_dw_documentary', 'src_free_documentary_travel', 'src_huntley_events', 'src_lse_sociology', 'src_thames_tv', 'src_timeline', 'src_toldinstone', 'src_travel_film_archive'},
    424: {'src_british_museum', 'src_business_casual', 'src_company_man', 'src_dw_documentary', 'src_economics_explained', 'src_economist', 'src_huntley_events', 'src_kings_and_generals', 'src_megaprojects', 'src_nfb', 'src_patrick_boyle', 'src_plain_bagel', 'src_school_of_life', 'src_thames_tv', 'src_timeline', 'src_toldinstone', 'src_two_cents'},
    469: {'src_berkman_klein', 'src_defcon', 'src_oii'},
    819: {'src_bbc_archive', 'src_british_movietone', 'src_chicago_film_archives', 'src_chm', 'src_huntley_events', 'src_huntley_industrial', 'src_thames_tv'},
    290: {'src_berkman_klein', 'src_bloomberg_originals', 'src_company_man', 'src_internet_historian', 'src_lgr', 'src_logically_answered', 'src_nerdwriter', 'src_oii', 'src_polyphonic'},
    837: {'src_all_the_stations', 'src_bbc_archive', 'src_huntley_architecture', 'src_huntley_events', 'src_huntley_transport', 'src_jago_hazzard', 'src_jay_leno', 'src_nrm', 'src_road_guy_rob', 'src_thames_tv'},
    838: {'src_all_the_stations', 'src_city_beautiful', 'src_huntley_architecture', 'src_huntley_motoring', 'src_huntley_transport', 'src_jago_hazzard', 'src_nrm', 'src_rail_relaxation'},
    882: {'src_thames_tv'},
    626: {'src_b1m', 'src_bloomberg_originals', 'src_business_casual', 'src_cnbc_documentary', 'src_cnbc_make_it', 'src_copa90', 'src_economics_explained', 'src_hbr', 'src_logically_answered', 'src_modern_mba'},
    610: {'src_bi_manufacturing', 'src_bloomberg_originals', 'src_bof', 'src_business_casual', 'src_cannes_lions', 'src_cnbc_documentary', 'src_cnbc_make_it', 'src_company_man', 'src_hbr', 'src_lbs', 'src_stanford_gsb', 'src_starter_story', 'src_ycombinator'},
    612: {'src_bof', 'src_business_casual', 'src_cnbc_documentary', 'src_company_man', 'src_hbr', 'src_logically_answered', 'src_modern_mba', 'src_plain_bagel', 'src_two_cents', 'src_wendover'},
    624: {'src_business_casual', 'src_climate_town', 'src_cnbc_documentary', 'src_dw_documentary', 'src_economics_explained', 'src_just_have_a_think', 'src_logically_answered', 'src_megaprojects', 'src_plain_bagel', 'src_thames_tv', 'src_wendover'},
    625: {'src_bloomberg_originals', 'src_bof', 'src_business_casual', 'src_cannes_lions', 'src_cnbc_documentary', 'src_cnbc_make_it', 'src_company_man', 'src_economics_explained', 'src_hbr', 'src_lbs', 'src_logically_answered', 'src_megaprojects', 'src_modern_mba', 'src_stanford_gsb', 'src_thames_tv'},
    697: {'src_alex_the_analyst', 'src_be_a_better_dev', 'src_cnbc_make_it', 'src_hbr', 'src_networkchuck', 'src_techworld_nana', 'src_ted', 'src_two_cents', 'src_ycombinator'},
    304: {'src_bundesliga', 'src_cna_insider', 'src_copa90', 'src_dw_documentary', 'src_england_football', 'src_premier_league'},
    306: {'src_bbc_archive', 'src_british_movietone', 'src_bundesliga', 'src_copa90', 'src_fifa', 'src_premier_league', 'src_thames_tv'},
    390: {'src_gcn', 'src_khan_medicine_physiology', 'src_running_channel'},
    391: {'src_gcn', 'src_nfl_films', 'src_royal_institution', 'src_running_channel', 'src_tom_merrick', 'src_uefa'},
    397: {'src_bundesliga', 'src_copa90', 'src_fifa', 'src_nfl_films', 'src_one', 'src_premier_league', 'src_top_rank', 'src_uefa'},
    717: {'src_adam_ragusea', 'src_atk', 'src_chef_jean_pierre', 'src_chuds_bbq', 'src_dianxi_xiaoge', 'src_eater', 'src_flo_chinyere', 'src_great_british_chefs', 'src_jamie_oliver', 'src_kenji', 'src_li_ziqi', 'src_made_with_lau', 'src_pasta_grannies', 'src_rick_bayless', 'src_sam_the_cooking_guy', 'src_tasting_history'},
    725: {'src_adam_ragusea', 'src_atk', 'src_chef_jean_pierre', 'src_chuds_bbq', 'src_eater', 'src_flo_chinyere', 'src_great_british_chefs', 'src_jamie_oliver', 'src_kenji', 'src_li_ziqi', 'src_made_with_lau', 'src_pasta_grannies', 'src_rainbow_plant_life', 'src_rick_bayless', 'src_sam_the_cooking_guy', 'src_tasting_history'},
    726: {'src_eater', 'src_great_british_chefs', 'src_jamie_oliver', 'src_kenji', 'src_made_with_lau', 'src_manjulas_kitchen', 'src_pasta_grannies', 'src_rick_bayless', 'src_tasting_history'},
    749: {'src_abc_news_indepth', 'src_cna_insider', 'src_cnbc_documentary', 'src_dw_documentary', 'src_frontline'},
    764: {'src_balu_nature', 'src_free_documentary_nature', 'src_kraig_adams', 'src_national_rail_scenic', 'src_nature_relaxation_films', 'src_rail_relaxation', 'src_relaxation_film', 'src_terra_mater'},
    778: {'src_architectural_digest', 'src_arte_travel', 'src_indigo_traveller', 'src_kara_and_nate', 'src_lost_leblanc'},
    767: {'src_bbc_archive', 'src_ben_felix', 'src_bloomberg_originals', 'src_city_beautiful', 'src_cnbc_documentary', 'src_economics_explained', 'src_exploring_alternatives', 'src_home_renovision', 'src_modern_mba', 'src_plain_bagel', 'src_this_old_house', 'src_two_cents'},
    440: {'src_bbc_earth', 'src_cna_insider', 'src_dw_documentary', 'src_free_documentary_nature', 'src_geologyhub', 'src_nick_zentner', 'src_pbs_terra', 'src_rai', 'src_real_wild', 'src_shawn_willsey', 'src_terra_mater', 'src_travel_film_archive', 'src_usgs'},
    449: {'src_british_museum', 'src_cna_insider', 'src_dw_documentary', 'src_eva_zu_beck', 'src_free_documentary_travel', 'src_lost_leblanc', 'src_timeline', 'src_travel_film_archive'},
    662: {'src_b1m', 'src_brick_immortar', 'src_casual_navigation', 'src_city_beautiful', 'src_engineering_rosie', 'src_hs2', 'src_network_rail', 'src_practical_engineering', 'src_road_guy_rob', 'src_wendover'},
    675: {'src_defcon', 'src_hagerty', 'src_huntley_transport', 'src_jay_leno', 'src_wendover'},
    192: {'src_movie_central'},
    187: {'src_movie_central'},
    143: {'src_filmrise_movies', 'src_movie_central', 'src_popcornflix'},
    184: {'src_mst3k'},
    129: {'src_rt_trailers'},
    233: {'src_gundam', 'src_tms_anime'},
    434: {'src_geography_now'},
    628: {'src_atk', 'src_bi_manufacturing', 'src_business_casual', 'src_cna_insider', 'src_cnbc_documentary', 'src_cnbc_make_it', 'src_company_man', 'src_dw_documentary', 'src_james_hoffmann', 'src_logically_answered', 'src_modern_mba', 'src_two_cents'},
    85: {'src_blogotheque', 'src_boiler_room', 'src_cercle', 'src_coachella', 'src_newport_folk', 'src_paste', 'src_rockpalast', 'src_toolroom', 'src_vp_records'},
    118: {'src_filmrise_movies', 'src_movie_central', 'src_popcornflix'},
    563: {'src_rick_beato'},
    37: {'src_movie_central', 'src_popcornflix'},
    141: {'src_film_detective'},
    145: {'src_film_detective'},
    116: {'src_nfb'},
    109: {'src_film_detective'},
    110: {'src_film_detective'},
    188: {'src_film_detective'},
    189: {'src_film_detective'},
    190: {'src_film_detective'},
}
